import { Injectable } from '@angular/core';
import { avv } from '../../components/angebot/avv.model';

@Injectable({
  providedIn: 'root'
})
export class AvvListeService {

  allAVV1: avv[] = [
    {value: '01', viewValue: 'Abfälle, die beim Aufsuchen, Ausbeuten und Gewinnen sowie bei der physikalischen und chemischen Behandlung von Bodenschätzen entstehen'},
    {value: '02', viewValue: 'Abfälle aus Landwirtschaft, Gartenbau, Teichwirtschaft, Forstwirtschaft, Jagd und Fischerei sowie der Herstellung und Verarbeitung von Nahrungsmitteln'},
    {value: '03', viewValue: 'Abfälle aus der Holzbearbeitung und der Herstellung von Platten, Möbeln, Zellstoffen, Papier und Pappe'},
    {value: '04', viewValue: 'Abfälle aus der Leder-, Pelz- und Textilindustrie'},
    {value: '05', viewValue: 'Abfälle aus der Erdölraffination, Erdgasreinigung und Kohlepyrolyse'},
    {value: '06', viewValue: 'Abfälle aus anorganisch-chemischen Prozessen'},
    {value: '07', viewValue: 'Abfälle aus organisch-chemischen Prozessen'},
    {value: '08', viewValue: 'Abfälle aus Herstellung, Zubereitung, Vertrieb und Anwendung (HZVA) von Beschichtungen (Farben, Lacke, Email), Klebstoffen, Dichtmassen und Druckfarben'},
    {value: '09', viewValue: 'Abfälle aus der fotografischen Industrie'},
    {value: '10', viewValue: 'Abfälle aus thermischen Prozessen'},
    {value: '11', viewValue: 'Abfälle aus der chemischen Oberflächenbearbeitung und Beschichtung von Metallen und anderen Werkstoffen; Nichteisenhydrometallurgie'},
    {value: '12', viewValue: 'Abfälle aus Prozessen der mechanischen Formgebung sowie der physikalischen und mechanischen Oberflächenbearbeitung vom Metallen und Kunststoffen'},
    {value: '13', viewValue: 'Ölabfälle und Abfälle aus flüssigen Brennstoffen (außer Speiseöle und Ölabfälle, die unter Kapitel 05, 12 oder 19 fallen)'},
    {value: '14', viewValue: 'Abfälle aus organischen Lösemitteln, Kühlmitteln und Treibgasen (außer Abfälle, die unter Kapitel 07 oder 08 fallen)'},
    {value: '15', viewValue: 'Verpackungsabfall, Aufsaugmassen, Wischtücher, Filtermaterialien und Schutzkleidung (a. n. g.)'},
    {value: '16', viewValue: 'Abfälle, die nicht anderswo im Verzeichnis aufgeführt sind'},
    {value: '17', viewValue: 'Bau- und Abbruchabfälle (einschließlich Aushub von verunreinigten Standorten)'},
    {value: '18', viewValue: 'Abfälle aus der humanmedizinischen oder tierärztlichen Versorgung und Forschung (ohne Küchen- und Restaurantabfälle, die nicht aus der unmittelbaren Krankenpflege stammen)'},
    {value: '19', viewValue: 'Abfälle aus Abfallbehandlungsanlagen, öffentlichen Abwasserbehandlungsanlagen sowie der Aufbereitung von Wasser für den menschlichen Gebrauch und Wasser für industrielle Zwecke'},
    {value: '20', viewValue: 'Siedlungsabfälle (Haushaltsabfälle und ähnliche gewerbliche und industrielle Abfälle sowie Abfälle aus Einrichtungen), einschließlich getrennt gesammelter Fraktionen'},
  ];

  allAVV2: avv[] = [
    {value: '01 01', viewValue: 'Abfälle aus dem Abbau von Bodenschätzen'},
    {value: '01 03', viewValue: 'Abfälle aus der physikalischen und chemischen Verarbeitung von metallhaltigen Bodenschätzen'},
    {value: '01 04', viewValue: 'Abfälle aus der physikalischen und chemischen Weiterverarbeitung von nichtmetallhaltigen Bodenschätzen'},
    {value: '01 05', viewValue: 'Bohrschlämme und andere Bohrabfälle'},
    {value: '02 01', viewValue: 'Abfälle aus Landwirtschaft, Gartenbau, Teichwirtschaft, Forstwirtschaft, Jagd und Fischerei'},
    {value: '02 02', viewValue: 'Abfälle aus der Zubereitung und Verarbeitung von Fleisch, Fisch und anderen Nahrungsmitteln tierischen Ursprungs'},
    {value: '02 03', viewValue: 'Abfälle aus der Zubereitung und Verarbeitung von Obst, Gemüse, Getreide, Speiseölen, Kakao, Kaffee, Tee und Tabak, aus der Konservenherstellung, der Herstellung von Hefe und Hefeextrakt sowie der Zubereitung und Fermentierung von Melasse'},
    {value: '02 04', viewValue: 'Abfälle aus der Zuckerherstellung'},
    {value: '02 05', viewValue: 'Abfälle aus der Milchverarbeitung'},
    {value: '02 06', viewValue: 'Abfälle aus der Herstellung von Back- und Süßwaren'},
    {value: '02 07', viewValue: 'Abfälle aus der Herstellung von alkoholischen und alkoholfreien Getränken (ohne Kaffee, Tee und Kakao)'},
    {value: '03 01', viewValue: 'Abfälle aus der Holzbearbeitung und der Herstellung von Platten und Möbeln'},
    {value: '03 02', viewValue: 'Abfälle aus der Holzkonservierung'},
    {value: '03 03', viewValue: 'Abfälle aus der Herstellung und Verarbeitung von Zellstoff, Papier, Karton und Pappe'},
    {value: '04 01', viewValue: 'Abfälle aus der Leder- und Pelzindustrie'},
    {value: '04 02', viewValue: 'Abfälle aus der Textilindustrie'},
    {value: '05 01', viewValue: 'Abfälle aus der Erdölraffination'},
    {value: '05 06', viewValue: 'Abfälle aus der Kohlepyrolyse'},
    {value: '05 07', viewValue: 'Abfälle aus Erdgasreinigung und -transport'},
    {value: '06 01', viewValue: 'Abfälle aus Herstellung, Zubereitung, Vertrieb und Anwendung (HZVA) von Säuren'},
    {value: '06 02', viewValue: 'Abfälle aus HZVA von Basen'},
    {value: '06 03', viewValue: 'Abfälle aus HZVA von Salzen, Salzlösungen und Metalloxiden'},
    {value: '06 04', viewValue: 'Metallhaltige Abfälle mit Ausnahme derjenigen, die unter 06 03 fallen'},
    {value: '06 05', viewValue: 'Schlämme aus der betriebseigenen Abwasserbehandlung'},
    {value: '06 06', viewValue: 'Abfälle aus HZVA von schwefelhaltigen Chemikalien, aus Schwefelchemie und Entschwefelungsprozessen'},
    {value: '06 07', viewValue: 'Abfälle aus HZVA von Halogenen und aus der Halogenchemie'},
    {value: '06 08', viewValue: 'Abfälle aus HZVA von Silicium und Siliciumverbindungen'},
    {value: '06 09', viewValue: 'Abfälle aus HZVA von phosphorhaltigen Chemikalien und aus der Phosphorchemie'},
    {value: '06 10', viewValue: 'Abfälle aus HZVA von stickstoffhaltigen Chemikalien, aus der Stickstoffchemie und der Herstellung von Düngemitteln'},
    {value: '06 11', viewValue: 'Abfälle aus der Herstellung von anorganischen Pigmenten und Farbgebern'},
    {value: '06 13', viewValue: 'Abfälle aus anorganisch-chemischen Prozessen a. n. g.'},
    {value: '07 01', viewValue: 'Abfälle aus Herstellung, Zubereitung, Vertrieb und Anwendung (HZVA) organischer Grundchemikalien'},
    {value: '07 02', viewValue: 'Abfälle aus HZVA von Kunststoffen, synthetischem Gummi und Kunstfasern'},
    {value: '07 03', viewValue: 'Abfälle aus HZVA von organischen Farbstoffen und Pigmenten (außer 06 11)'},
    {value: '07 04', viewValue: 'Abfälle aus HZVA von organischen Pflanzenschutzmitteln (außer 02 01 08 und 02 01 09), Holzschutzmitteln (außer 03 02) und anderen Bioziden'},
    {value: '07 05', viewValue: 'Abfälle aus HZVA von Pharmazeutika'},
    {value: '07 06', viewValue: 'Abfälle aus HZVA von Fetten, Schmierstoffen, Seifen, Waschmitteln, Desinfektionsmitteln und Körperpflegemitteln'},
    {value: '07 07', viewValue: 'Abfälle aus HZVA von Feinchemikalien und Chemikalien a. n. g.'},
    {value: '08 01', viewValue: 'Abfälle aus HZVA und Entfernung von Farben und Lacken'},
    {value: '08 02', viewValue: 'Abfälle aus HZVA anderer Beschichtungen (einschließlich keramischer Werkstoffe)'},
    {value: '08 03', viewValue: 'Abfälle aus HZVA von Druckfarben'},
    {value: '08 04', viewValue: 'Abfälle aus HZVA von Klebstoffen und Dichtmassen (einschließlich wasserabweisender Materialien)'},
    {value: '08 05', viewValue: 'Nicht unter 08 aufgeführte Abfälle'},
    {value: '09 01', viewValue: 'Abfälle aus der fotografischen Industrie'},
    { value: '10 01', viewValue: 'Abfälle aus Kraftwerken und anderen Verbrennungsanlagen (außer 19)' },
    { value: '10 02', viewValue: 'Abfälle aus der Eisen- und Stahlindustrie' },
    { value: '10 03', viewValue: 'Abfälle aus der thermischen Aluminium-Metallurgie' },
    { value: '10 04', viewValue: 'Abfälle aus der thermischen Bleimetallurgie' },
    { value: '10 05', viewValue: 'Abfälle aus der thermischen Zinkmetallurgie' },
    { value: '10 06', viewValue: 'Abfälle aus der thermischen Kupfermetallurgie' },
    { value: '10 07', viewValue: 'Abfälle aus der thermischen Silber-, Gold- und Platinmetallurgie' },
    { value: '10 08', viewValue: 'Abfälle aus sonstiger thermischer Nichteisenmetallurgie' },
    { value: '10 09', viewValue: 'Abfälle vom Gießen von Eisen und Stahl' },
    { value: '10 10', viewValue: 'Abfälle vom Gießen von Nichteisenmetallen' },
    { value: '10 11', viewValue: 'Abfälle aus der Herstellung von Glas und Glaserzeugnissen' },
    { value: '10 12', viewValue: 'Abfälle aus der Herstellung von Keramikerzeugnissen und keramischen Baustoffen wie Ziegeln, Fliesen, Steinzeug' },
    { value: '10 13', viewValue: 'Abfälle aus der Herstellung von Zement, Branntkalk, Gips und Erzeugnissen aus diesen' },
    { value: '10 14', viewValue: 'Abfälle aus Krematorien'},
    { value: '11 01', viewValue: 'Abfälle aus der chemischen Oberflächenbearbeitung und Beschichtung von Metallen und anderen Werkstoffen (z.B. Galvanik, Verzinkung, Beizen, Ätzen, Phosphatieren, alkalisches Entfetten und Anodisierung)' },
    { value: '11 02', viewValue: 'Abfälle aus Prozessen der Nichteisen-Hydrometallurgie' },
    { value: '11 03', viewValue: 'Schlämme und Feststoffe aus Härteprozessen' },
    { value: '11 05', viewValue: 'Abfälle aus Prozessen der thermischen Verzinkung' },
    { value: '12 01', viewValue: 'Abfälle aus Prozessen der mechanischen Formgebung sowie der physikalischen und mechanischen Oberflächenbearbeitung von Metallen und Kunststoffen' },
    { value: '12 03', viewValue: 'Abfälle aus der Wasser- und Dampfentfettung (außer 11)' },
    { value: '13 01', viewValue: 'Abfälle von Hydraulikölen' },
  { value: '13 02', viewValue: 'Abfälle von Maschinen-, Getriebe- und Schmierölen' },
  { value: '13 03', viewValue: 'Abfälle von Isolier- und Wärmeübertragungsölen' },
  { value: '13 04', viewValue: 'Bilgenöle' },
  { value: '13 05', viewValue: 'Inhalte von Öl-/Wasserabscheidern' },
  { value: '13 07', viewValue: 'Abfälle aus flüssigen Brennstoffen' },
  { value: '13 08', viewValue: 'Ölabfälle a. n. g.' },
  { value: '14 06', viewValue: 'Abfälle aus organischen Lösemitteln, Kühlmitteln sowie Schaum- und Aerosoltreibgasen' },
  { value: '15 01', viewValue: 'Verpackungen (einschließlich getrennt gesammelter kommunaler Verpackungsabfälle)' },
  { value: '15 02', viewValue: 'Aufsaug- und Filtermaterialien, Wischtücher und Schutzkleidung' },
  { value: '16 01', viewValue: 'Altfahrzeuge verschiedener Verkehrsträger (einschließlich mobiler Maschinen) und Abfälle aus der Demontage von Altfahrzeugen sowie der Fahrzeugwartung (außer 13, 14, 16 06 und 16 08)' },
  { value: '16 02', viewValue: 'Elektrische und elektronische Geräte und deren Bauteile' },
  { value: '16 03', viewValue: 'Fehlchargen und ungebrauchte Erzeugnisse' },
  { value: '16 04', viewValue: 'Explosivabfälle' },
  { value: '16 05', viewValue: 'Gase in Druckbehältern und gebrauchte Chemikalien' },
  { value: '16 06', viewValue: 'Batterien und Akkumulatoren' },
  { value: '16 07', viewValue: 'Abfälle aus der Reinigung von Transport- und Lagertanks und Fässern (außer 05 und 13)' },
  { value: '16 08', viewValue: 'Gebrauchte Katalysatoren' },
  { value: '16 09', viewValue: 'Oxidierende Stoffe' },
  { value: '16 10', viewValue: 'Wässrige flüssige Abfälle zur externen Behandlung' },
  { value: '16 11', viewValue: 'Gebrauchte Auskleidungen und feuerfeste Materialien' },
  { value: '17 01', viewValue: 'Beton, Ziegel, Fliesen und Keramik' },
  { value: '17 02', viewValue: 'Holz, Glas und Kunststoff' },
  { value: '17 03', viewValue: 'Bitumengemische, Kohlenteer und teerhaltige Produkte' },
  { value: '17 04', viewValue: 'Metalle (einschließlich Legierungen)' },
  { value: '17 05', viewValue: 'Boden (einschließlich Aushub von verunreinigten Standorten), Steine und Baggergut' },
  { value: '17 06', viewValue: 'Dämmmaterial und asbesthaltige Baustoffe' },
  { value: '17 08', viewValue: 'Baustoffe auf Gipsbasis' },
  { value: '17 09', viewValue: 'Sonstige Bau- und Abbruchabfälle' },
  { value: '18 01', viewValue: 'Abfälle aus der humanmedizinischen oder tierärztlichen Versorgung und Forschung (ohne Küchen- und Restaurantabfälle, die nicht aus der unmittelbaren Krankenpflege stammen)' },
  { value: '18 02', viewValue: 'Abfälle aus Forschung, Diagnose, Krankenbehandlung und Vorsorge bei Tieren' },
  { value: '19 01', viewValue: 'Abfälle aus der Verbrennung oder Pyrolyse von Abfällen' },
  { value: '19 02', viewValue: 'Abfälle aus der physikalisch-chemischen Behandlung von Abfällen (einschließlich Dechromatisierung, Cyanidentfernung, Neutralisation)' },
  { value: '19 03', viewValue: 'Stabilisierte und verfestigte Abfälle' },
  { value: '19 04', viewValue: 'Verglaste Abfälle und Abfälle aus der Verglasung' },
  { value: '19 05', viewValue: 'Abfälle aus der aeroben Behandlung von festen Abfällen' },
  { value: '19 06', viewValue: 'Abfälle aus der anaeroben Behandlung von Abfällen' },
  { value: '19 07', viewValue: 'Deponiesickerwasser' },
  { value: '19 08', viewValue: 'Abfälle aus Abwasserbehandlungsanlagen a. n. g.' },
  { value: '19 09', viewValue: 'Abfälle aus der Zubereitung von Wasser für den menschlichen Gebrauch oder industriellem Brauchwasser' },
  { value: '19 10', viewValue: 'Abfälle aus dem Schreddern von metallhaltigen Abfällen' },
  { value: '19 11', viewValue: 'Abfälle aus der Altölaufbereitung' },
  { value: '19 12', viewValue: 'Abfälle aus der mechanischen Behandlung von Abfällen (z. B. Sortieren, Zerkleinern, Verdichten, Pelletieren) a. n. g.' },
  { value: '19 13', viewValue: 'Abfälle aus der Sanierung von Böden und Grundwasser' },
  { value: '20 01', viewValue: 'Siedlungsabfälle (Haushaltsabfälle und ähnliche gewerbliche und industrielle Abfälle sowie Abfälle aus Einrichtungen), einschließlich getrennt gesammelter Fraktionen' },
  { value: '20 02', viewValue: 'Garten- und Parkabfälle (einschließlich Friedhofsabfälle)' },
  { value: '20 03', viewValue: 'Andere Siedlungsabfälle' },
  ];

  allAVV3: avv[] = [
  { value: '01 01 01', viewValue: 'Abfälle aus dem Abbau von metallhaltigen Bodenschätzen' },
  { value: '01 01 02', viewValue: 'Abfälle aus dem Abbau von nichtmetallhaltigen Bodenschätzen' },
  { value: '01 03 04', viewValue: 'Säure bildende Aufbereitungsrückstände aus der Verarbeitung von sulfidischem Erz' },
  { value: '01 03 05', viewValue: 'andere Aufbereitungsrückstände, die gefährliche Stoffe enthalten' },
  { value: '01 03 06', viewValue: 'Aufbereitungsrückstände mit Ausnahme derjenigen, die unter 01 03 04 und 01 03 05 fallen' },
  { value: '01 03 07', viewValue: 'andere, gefährliche Stoffe enthaltende Abfälle aus der physikalischen und chemischen Verarbeitung von metallhaltigen Bodenschätzen' },
  { value: '01 03 08', viewValue: 'staubende und pulvrige Abfälle mit Ausnahme derjenigen, die unter 01 03 07 fallen' },
  { value: '01 03 09', viewValue: 'Rotschlamm aus der Aluminiumoxidherstellung mit Ausnahme von Abfällen, die unter 01 03 10 fallen' },
  { value: '01 03 10', viewValue: 'Rotschlamm aus der Aluminiumoxidherstellung, der gefährliche Stoffe enthält, mit Ausnahme der unter 01 03 07 genannten Abfälle' },
  { value: '01 03 99', viewValue: 'Abfälle a. n. g.' },
  { value: '01 04 07', viewValue: 'gefährliche Stoffe enthaltende Abfälle aus der physikalischen und chemischen Weiterverarbeitung von nichtmetallhaltigen Bodenschätzen' },
  { value: '01 04 08', viewValue: 'Abfälle von Kies- und Gesteinsbruch mit Ausnahme derjenigen, die unter 01 04 07 fallen' },
  { value: '01 04 09', viewValue: 'Abfälle von Sand und Ton' },
  { value: '01 04 10', viewValue: 'staubende und pulvrige Abfälle mit Ausnahme derjenigen, die unter 01 04 07 fallen' },
  { value: '01 04 11', viewValue: 'Abfälle aus der Verarbeitung von Kali- und Steinsalz mit Ausnahme derjenigen, die unter 01 04 07 fallen' },
  { value: '01 04 12', viewValue: 'Aufbereitungsrückstände und andere Abfälle aus der Wäsche und Reinigung von Bodenschätzen mit Ausnahme derjenigen, die unter 01 04 07 und 01 04 11 fallen' },
  { value: '01 04 13', viewValue: 'Abfälle aus Steinmetz- und -sägearbeiten mit Ausnahme derjenigen, die unter 01 04 07 fallen' },
  { value: '01 04 99', viewValue: 'Abfälle a. n. g.' },
  { value: '01 05 04', viewValue: 'Schlämme und Abfälle aus Süßwasserbohrungen' },
  { value: '01 05 05', viewValue: 'ölhaltige Bohrschlämme und -abfälle' },
  { value: '01 05 06', viewValue: 'Bohrschlämme und andere Bohrabfälle, die gefährliche Stoffe enthalten' },
  { value: '01 05 07', viewValue: 'barythaltige Bohrschlämme und -abfälle mit Ausnahme derjenigen, die unter 01 05 05 und 01 05 06 fallen' },
  { value: '01 05 08', viewValue: 'chloridhaltige Bohrschlämme und -abfälle mit Ausnahme derjenigen, die unter 01 05 05 und 01 05 06 fallen' },
  { value: '01 05 99', viewValue: 'Abfälle a. n. g.' },
  { value: '02 01 01', viewValue: 'Schlämme von Wasch- und Reinigungsvorgängen' },
  { value: '02 01 02', viewValue: 'Abfälle aus tierischem Gewebe' },
  { value: '02 01 03', viewValue: 'Abfälle aus pflanzlichem Gewebe' },
  { value: '02 01 04', viewValue: 'Kunststoffabfälle (ohne Verpackungen)' },
  { value: '02 01 06', viewValue: 'tierische Ausscheidungen, Gülle/Jauche und Stallmist (einschließlich verdorbenes Stroh), Abwässer, getrennt gesammelt und extern behandelt' },
  { value: '02 01 07', viewValue: 'Abfälle aus der Forstwirtschaft' },
  { value: '02 01 08', viewValue: 'Abfälle von Chemikalien für die Landwirtschaft, die gefährliche Stoffe enthalten' },
  { value: '02 01 09', viewValue: 'Abfälle von Chemikalien für die Landwirtschaft mit Ausnahme derjenigen, die unter 02 01 08 fallen' },
  { value: '02 01 10', viewValue: 'Metallabfälle' },
  { value: '02 01 99', viewValue: 'Abfälle a. n. g.' },
  { value: '02 02 01', viewValue: 'Schlämme von Wasch- und Reinigungsvorgängen' },
  { value: '02 02 02', viewValue: 'Abfälle aus tierischem Gewebe' },
  { value: '02 02 03', viewValue: 'für Verzehr oder Verarbeitung ungeeignete Stoffe' },
  { value: '02 02 04', viewValue: 'Schlämme aus der betriebseigenen Abwasserbehandlung' },
  { value: '02 02 99', viewValue: 'Abfälle a. n. g.' },
  { value: '02 03 01', viewValue: 'Schlämme aus Wasch-, Reinigungs-, Schäl-, Zentrifugier- und Abtrennprozessen' },
  { value: '02 03 02', viewValue: 'Abfälle von Konservierungsstoffen' },
  { value: '02 03 03', viewValue: 'Abfälle aus der Extraktion mit Lösemitteln' },
  { value: '02 03 04', viewValue: 'für Verzehr oder Verarbeitung ungeeignete Stoffe' },
  { value: '02 03 05', viewValue: 'Schlämme aus der betriebseigenen Abwasserbehandlung' },
  { value: '02 03 99', viewValue: 'Abfälle a. n. g.' },
  { value: '02 04 01', viewValue: 'Rübenerde' },
  { value: '02 04 02', viewValue: 'nicht spezifikationsgerechter Calciumcarbonatschlamm' },
  { value: '02 04 03', viewValue: 'Schlämme aus der betriebseigenen Abwasserbehandlung' },
  { value: '02 04 99', viewValue: 'Abfälle a. n. g.' },
  { value: '02 05 01', viewValue: 'für Verzehr oder Verarbeitung ungeeignete Stoffe' },
  { value: '02 05 02', viewValue: 'Schlämme aus der betriebseigenen Abwasserbehandlung' },
  { value: '02 05 99', viewValue: 'Abfälle a. n. g.' },
  { value: '02 06 01', viewValue: 'für Verzehr oder Verarbeitung ungeeignete Stoffe' },
  { value: '02 06 02', viewValue: 'Abfälle von Konservierungsstoffen' },
  { value: '02 06 03', viewValue: 'Schlämme aus der betriebseigenen Abwasserbehandlung' },
  { value: '02 06 99', viewValue: 'Abfälle a. n. g.' },
  { value: '02 07 01', viewValue: 'Abfälle aus der Wäsche, Reinigung und mechanischen Zerkleinerung des Rohmaterials' },
  { value: '02 07 02', viewValue: 'Abfälle aus der Alkoholdestillation' },
  { value: '02 07 03', viewValue: 'Abfälle aus der chemischen Behandlung' },
  { value: '02 07 04', viewValue: 'für Verzehr oder Verarbeitung ungeeignete Stoffe' },
  { value: '02 07 05', viewValue: 'Schlämme aus der betriebseigenen Abwasserbehandlung' },
  { value: '02 07 99', viewValue: 'Abfälle a. n. g.' },
    { value: '03 01 01', viewValue: 'Rinden- und Korkabfälle' },
  { value: '03 01 04', viewValue: 'Sägemehl, Späne, Abschnitte, Holz, Spanplatten und Furniere, die gefährliche Stoffe enthalten' },
  { value: '03 01 05', viewValue: 'Sägemehl, Späne, Abschnitte, Holz, Spanplatten und Furniere mit Ausnahme derjenigen, die unter 03 01 04 fallen' },
  { value: '03 01 99', viewValue: 'Abfälle a. n. g.' },
  { value: '03 02 01', viewValue: 'halogenfreie organische Holzschutzmittel' },
  { value: '03 02 02', viewValue: 'chlororganische Holzschutzmittel' },
  { value: '03 02 03', viewValue: 'metallorganische Holzschutzmittel' },
  { value: '03 02 04', viewValue: 'anorganische Holzschutzmittel' },
  { value: '03 02 05', viewValue: 'andere Holzschutzmittel, die gefährliche Stoffe enthalten' },
  { value: '03 02 99', viewValue: 'Holzschutzmittel a. n. g.' },
  { value: '03 03 01', viewValue: 'Rinden- und Holzabfälle' },
  { value: '03 03 02', viewValue: 'Sulfitschlämme (aus der Rückgewinnung von Kochlaugen)' },
  { value: '03 03 05', viewValue: 'De-inking-Schlämme aus dem Papierrecycling' },
  { value: '03 03 07', viewValue: 'mechanisch abgetrennte Abfälle aus der Auflösung von Papier- und Pappabfällen' },
  { value: '03 03 08', viewValue: 'Abfälle aus dem Sortieren von Papier und Pappe für das Recycling' },
  { value: '03 03 09', viewValue: 'Kalkschlammabfälle' },
  { value: '03 03 10', viewValue: 'Faserabfälle, Faser-, Füller- und Überzugsschlämme aus der mechanischen Abtrennung' },
  { value: '03 03 11', viewValue: 'Schlämme aus der betriebseigenen Abwasserbehandlung mit Ausnahme derjenigen, die unter 03 03 10 fallen' },
  { value: '03 03 99', viewValue: 'Abfälle a. n. g.' },
  { value: '04 01 01', viewValue: 'Fleischabschabungen und Häuteabfälle' },
  { value: '04 01 02', viewValue: 'geäschertes Leimleder' },
  { value: '04 01 03', viewValue: 'Entfettungsabfälle, lösemittelhaltig, ohne flüssige Phase' },
  { value: '04 01 04', viewValue: 'chromhaltige Gerbereibrühe' },
  { value: '04 01 05', viewValue: 'chromfreie Gerbereibrühe' },
  { value: '04 01 06', viewValue: 'chromhaltige Schlämme, insbesondere aus der betriebseigenen Abwasserbehandlung' },
  { value: '04 01 07', viewValue: 'chromfreie Schlämme, insbesondere aus der betriebseigenen Abwasserbehandlung' },
  { value: '04 01 08', viewValue: 'chromhaltige Abfälle aus gegerbtem Leder (Abschnitte, Schleifstaub, Falzspäne)' },
  { value: '04 01 09', viewValue: 'Abfälle aus der Zurichtung und dem Finish' },
  { value: '04 01 99', viewValue: 'Abfälle a. n. g.' },
  { value: '04 02 09', viewValue: 'Abfälle aus Verbundmaterialien (imprägnierte Textilien, Elastomer, Plastomer)' },
  { value: '04 02 10', viewValue: 'organische Stoffe aus Naturstoffen (z.B. Fette, Wachse)' },
  { value: '04 02 14', viewValue: 'Abfälle aus dem Finish, die organische Lösungsmittel enthalten' },
  { value: '04 02 15', viewValue: 'Abfälle aus dem Finish mit Ausnahme derjenigen, die unter 04 02 14 fallen' },
  { value: '04 02 16', viewValue: 'Farbstoffe und Pigmente, die gefährliche Stoffe enthalten' },
  { value: '04 02 17', viewValue: 'Farbstoffe und Pigmente mit Ausnahme derjenigen, die unter 04 02 16 fallen' },
  { value: '04 02 19', viewValue: 'Schlämme aus der betriebseigenen Abwasserbehandlung, die gefährliche Stoffe enthalten' },
  { value: '04 02 20', viewValue: 'Schlämme aus der betriebseigenen Abwasserbehandlung mit Ausnahme derjenigen, die unter 04 02 19 fallen' },
  { value: '04 02 21', viewValue: 'Abfälle aus unbehandelten Textilfasern' },
  { value: '04 02 22', viewValue: 'Abfälle aus verarbeiteten Textilfasern' },
  { value: '04 02 99', viewValue: 'Abfälle a. n. g.' },
  { value: '05 01 02', viewValue: 'Entsalzungsschlämme' },
  { value: '05 01 03', viewValue: 'Bodenschlämme aus Tanks' },
  { value: '05 01 04', viewValue: 'saure Alkylschlämme' },
  { value: '05 01 05', viewValue: 'verschüttetes Öl' },
  { value: '05 01 06', viewValue: 'ölhaltige Schlämme aus Betriebsvorgängen und Instandhaltung' },
  { value: '05 01 07', viewValue: 'Säureteere' },
  { value: '05 01 08', viewValue: 'andere Teere' },
  { value: '05 01 09', viewValue: 'Schlämme aus der betriebseigenen Abwasserbehandlung, die gefährliche Stoffe enthalten' },
  { value: '05 01 10', viewValue: 'Schlämme aus der betriebseigenen Abwasserbehandlung mit Ausnahme derjenigen, die unter 05 01 09 fallen' },
  { value: '05 01 11', viewValue: 'Abfälle aus der Brennstoffreinigung mit Basen' },
  { value: '05 01 12', viewValue: 'säurehaltige Öle' },
  { value: '05 01 13', viewValue: 'Schlämme aus der Kesselspeisewasseraufbereitung' },
  { value: '05 01 14', viewValue: 'Abfälle aus Kühlkolonnen' },
  { value: '05 01 15', viewValue: 'gebrauchte Filtertone' },
  { value: '05 01 16', viewValue: 'schwefelhaltige Abfälle aus der Ölentschwefelung' },
  { value: '05 01 17', viewValue: 'Bitumen' },
  { value: '05 01 99', viewValue: 'Abfälle a. n. g.' },
  { value: '05 06 01', viewValue: 'Säureteere' },
  { value: '05 06 03', viewValue: 'andere Teere' },
  { value: '05 06 04', viewValue: 'Abfälle aus Kühlkolonnen' },
  { value: '05 06 99', viewValue: 'Abfälle a. n. g.' },
  { value: '05 07 01', viewValue: 'quecksilberhaltige Abfälle' },
  { value: '05 07 02', viewValue: 'schwefelhaltige Abfälle' },
  { value: '05 07 99', viewValue: 'Abfälle a. n. g.' },
  { value: '06 01 01', viewValue: 'Schwefelsäure und schweflige Säure' },
  { value: '06 01 02', viewValue: 'Salzsäure' },
  { value: '06 01 03', viewValue: 'Flusssäure' },
  { value: '06 01 04', viewValue: 'Phosphorsäure und phosphorige Säure' },
  { value: '06 01 05', viewValue: 'Salpetersäure und salpetrige Säure' },
  { value: '06 01 06', viewValue: 'andere Säuren' },
  { value: '06 01 99', viewValue: 'Abfälle a. n. g.' },
  { value: '06 02 01', viewValue: 'Calciumhydroxid' },
  { value: '06 02 03', viewValue: 'Ammoniumhydroxid' },
  { value: '06 02 04', viewValue: 'Natrium- und Kaliumhydroxid' },
  { value: '06 02 05', viewValue: 'andere Basen' },
  { value: '06 02 99', viewValue: 'Abfälle a. n. g.' },
  { value: '06 03 11', viewValue: 'feste Salze und Lösungen, die Cyanid enthalten' },
  { value: '06 03 13', viewValue: 'feste Salze und Lösungen, die Schwermetalle enthalten' },
  { value: '06 03 14', viewValue: 'feste Salze und Lösungen mit Ausnahme derjenigen, die unter 06 03 11 und 06 03 13 fallen' },
  { value: '06 03 15', viewValue: 'Metalloxide, die Schwermetalle enthalten' },
  { value: '06 03 16', viewValue: 'Metalloxide mit Ausnahme derjenigen, die unter 06 03 15 fallen' },
  { value: '06 03 99', viewValue: 'Abfälle a. n. g.' },
  { value: '06 04 03', viewValue: 'arsenhaltige Abfälle' },
  { value: '06 04 04', viewValue: 'quecksilberhaltige Abfälle' },
  { value: '06 04 05', viewValue: 'Abfälle, die andere Schwermetalle enthalten' },
  { value: '06 04 99', viewValue: 'Abfälle a. n. g.' },
  { value: '06 05 02', viewValue: 'Schlämme aus der betriebseigenen Abwasserbehandlung, die gefährliche Stoffe enthalten' },
  { value: '06 05 03', viewValue: 'Schlämme aus der betriebseigenen Abwasserbehandlung mit Ausnahme derjenigen, die unter 06 05 02 fallen' },
  { value: '06 06 02', viewValue: 'Abfälle, die gefährliche Sulfide enthalten' },
  { value: '06 06 03', viewValue: 'sulfidhaltige Abfälle mit Ausnahme derjenigen, die unter 06 06 02 fallen' },
  { value: '06 06 99', viewValue: 'Abfälle a. n. g.' },
  { value: '06 07 01', viewValue: 'asbesthaltige Abfälle aus der Elektrolyse' },
  { value: '06 07 02', viewValue: 'Aktivkohle aus der Chlorherstellung' },
  { value: '06 07 03', viewValue: 'quecksilberhaltige Bariumsulfatschlämme' },
  { value: '06 07 04', viewValue: 'Lösungen und Säuren, z.B. Kontaktsäure' },
  { value: '06 07 99', viewValue: 'Abfälle a. n. g.' },
  { value: '06 08 02', viewValue: 'Abfälle, die gefährliche Chlorsilane enthalten' },
  { value: '06 08 99', viewValue: 'Abfälle a. n. g.' },
  { value: '06 09 02', viewValue: 'phosphorhaltige Schlacke' },
  { value: '06 09 03', viewValue: 'Reaktionsabfälle auf Calciumbasis, die gefährliche Stoffe enthalten oder durch gefährliche Stoffe verunreinigt sind' },
  { value: '06 09 04', viewValue: 'Reaktionsabfälle auf Calciumbasis mit Ausnahme derjenigen, die unter 06 09 03 fallen' },
  { value: '06 09 99', viewValue: 'Abfälle a. n. g.' },
  { value: '06 10 02', viewValue: 'Abfälle, die gefährliche Stoffe enthalten' },
  { value: '06 10 99', viewValue: 'Abfälle a. n. g.' },
  { value: '06 11 01', viewValue: 'Reaktionsabfälle auf Calciumbasis aus der Titandioxidherstellung' },
  { value: '06 11 99', viewValue: 'Abfälle a. n. g.' },
  { value: '06 13 01', viewValue: 'anorganische Pflanzenschutzmittel, Holzschutzmittel und andere Biozide' },
  { value: '06 13 02', viewValue: 'gebrauchte Aktivkohle (außer 06 07 02)' },
  { value: '06 13 03', viewValue: 'Industrieruß' },
  { value: '06 13 04', viewValue: 'Abfälle aus der Asbestverarbeitung' },
  { value: '06 13 05', viewValue: 'Ofen- und Kaminruß' },
  { value: '06 13 99', viewValue: 'Abfälle a. n. g.' },
  { value: '07 01 01', viewValue: 'wässrige Waschflüssigkeiten und Mutterlaugen' },
  { value: '07 01 03', viewValue: 'halogenorganische Lösemittel, Waschflüssigkeiten und Mutterlaugen' },
  { value: '07 01 04', viewValue: 'andere organische Lösemittel, Waschflüssigkeiten und Mutterlaugen' },
  { value: '07 01 07', viewValue: 'halogenierte Reaktions- und Destillationsrückstände' },
  { value: '07 01 08', viewValue: 'andere Reaktions- und Destillationsrückstände' },
  { value: '07 01 09', viewValue: 'halogenierte Filterkuchen, gebrauchte Aufsaugmaterialien' },
  { value: '07 01 10', viewValue: 'andere Filterkuchen, gebrauchte Aufsaugmaterialien' },
  { value: '07 01 11', viewValue: 'Schlämme aus der betriebseigenen Abwasserbehandlung, die gefährliche Stoffe enthalten' },
  { value: '07 01 12', viewValue: 'Schlämme aus der betriebseigenen Abwasserbehandlung mit Ausnahme derjenigen, die unter 07 01 11 fallen' },
  { value: '07 01 99', viewValue: 'Abfälle a. n. g.' },
  { value: '07 02 01', viewValue: 'wässrige Waschflüssigkeiten und Mutterlaugen' },
  { value: '07 02 03', viewValue: 'halogenorganische Lösemittel, Waschflüssigkeiten und Mutterlaugen' },
  { value: '07 02 04', viewValue: 'andere organische Lösemittel, Waschflüssigkeiten und Mutterlaugen' },
  { value: '07 02 07', viewValue: 'halogenierte Reaktions- und Destillationsrückstände' },
  { value: '07 02 08', viewValue: 'andere Reaktions- und Destillationsrückstände' },
  { value: '07 02 09', viewValue: 'halogenierte Filterkuchen, gebrauchte Aufsaugmaterialien' },
  { value: '07 02 10', viewValue: 'andere Filterkuchen, gebrauchte Aufsaugmaterialien' },
  { value: '07 02 11', viewValue: 'Schlämme aus der betriebseigenen Abwasserbehandlung, die gefährliche Stoffe enthalten' },
  { value: '07 02 12', viewValue: 'Schlämme aus der betriebseigenen Abwasserbehandlung mit Ausnahme derjenigen, die unter 07 02 11 fallen' },
  { value: '07 02 13', viewValue: 'Kunststoffabfälle' },
  { value: '07 02 14', viewValue: 'Abfälle von Zusatzstoffen, die gefährliche Stoffe enthalten' },
  { value: '07 02 15', viewValue: 'Abfälle von Zusatzstoffen mit Ausnahme derjenigen, die unter 07 02 14 fallen' },
  { value: '07 02 16', viewValue: 'Abfälle, die gefährliche Silicone enthalten' },
  { value: '07 02 17', viewValue: 'siliconhaltige Abfälle, andere als die in 07 02 16 genannten' },
  { value: '07 02 99', viewValue: 'Abfälle a. n. g.' },
  { value: '07 03 01', viewValue: 'wässrige Waschflüssigkeiten und Mutterlaugen' },
  { value: '07 03 03', viewValue: 'halogenorganische Lösemittel, Waschflüssigkeiten und Mutterlaugen' },
  { value: '07 03 04', viewValue: 'andere organische Lösemittel, Waschflüssigkeiten und Mutterlaugen' },
  { value: '07 03 07', viewValue: 'halogenierte Reaktions- und Destillationsrückstände' },
  { value: '07 03 08', viewValue: 'andere Reaktions- und Destillationsrückstände' },
  { value: '07 03 09', viewValue: 'halogenierte Filterkuchen, gebrauchte Aufsaugmaterialien' },
  { value: '07 03 10', viewValue: 'andere Filterkuchen, gebrauchte Aufsaugmaterialien' },
  { value: '07 03 11', viewValue: 'Schlämme aus der betriebseigenen Abwasserbehandlung, die gefährliche Stoffe enthalten' },
  { value: '07 03 12', viewValue: 'Schlämme aus der betriebseigenen Abwasserbehandlung mit Ausnahme derjenigen, die unter 07 03 11 fallen' },
  { value: '07 03 99', viewValue: 'Abfälle a. n. g.' },
  { value: '07 04 01', viewValue: 'wässrige Waschflüssigkeiten und Mutterlaugen' },
  { value: '07 04 03', viewValue: 'halogenorganische Lösemittel, Waschflüssigkeiten und Mutterlaugen' },
  { value: '07 04 04', viewValue: 'andere organische Lösemittel, Waschflüssigkeiten und Mutterlaugen' },
  { value: '07 04 07', viewValue: 'halogenierte Reaktions- und Destillationsrückstände' },
  { value: '07 04 08', viewValue: 'andere Reaktions- und Destillationsrückstände' },
  { value: '07 04 09', viewValue: 'halogenierte Filterkuchen, gebrauchte Aufsaugmaterialien' },
  { value: '07 04 10', viewValue: 'andere Filterkuchen, gebrauchte Aufsaugmaterialien' },
  { value: '07 04 11', viewValue: 'Schlämme aus der betriebseigenen Abwasserbehandlung, die gefährliche Stoffe enthalten' },
  { value: '07 04 12', viewValue: 'Schlämme aus der betriebseigenen Abwasserbehandlung mit Ausnahme derjenigen, die unter 07 04 11 fallen' },
  { value: '07 04 13', viewValue: 'feste Abfälle, die gefährliche Stoffe enthalten' },
  { value: '07 04 99', viewValue: 'Abfälle a. n. g.' },
  { value: '07 05 01', viewValue: 'wässrige Waschflüssigkeiten und Mutterlaugen' },
  { value: '07 05 03', viewValue: 'halogenorganische Lösemittel, Waschflüssigkeiten und Mutterlaugen' },
  { value: '07 05 04', viewValue: 'andere organische Lösemittel, Waschflüssigkeiten und Mutterlaugen' },
  { value: '07 05 07', viewValue: 'halogenierte Reaktions- und Destillationsrückstände' },
  { value: '07 05 08', viewValue: 'andere Reaktions- und Destillationsrückstände' },
  { value: '07 05 09', viewValue: 'halogenierte Filterkuchen, gebrauchte Aufsaugmaterialien' },
  { value: '07 05 10', viewValue: 'andere Filterkuchen, gebrauchte Aufsaugmaterialien' },
  { value: '07 05 11', viewValue: 'Schlämme aus der betriebseigenen Abwasserbehandlung, die gefährliche Stoffe enthalten' },
  { value: '07 05 12', viewValue: 'Schlämme aus der betriebseigenen Abwasserbehandlung mit Ausnahme derjenigen, die unter 07 05 11 fallen' },
  { value: '07 05 13', viewValue: 'feste Abfälle, die gefährliche Stoffe enthalten' },
  { value: '07 05 14', viewValue: 'feste Abfälle mit Ausnahme derjenigen, die unter 07 05 13 fallen' },
  { value: '07 05 99', viewValue: 'Abfälle a. n. g.' },
  { value: '07 06 01', viewValue: 'wässrige Waschflüssigkeiten und Mutterlaugen' },
  { value: '07 06 03', viewValue: 'halogenorganische Lösemittel, Waschflüssigkeiten und Mutterlaugen' },
  { value: '07 06 04', viewValue: 'andere organische Lösemittel, Waschflüssigkeiten und Mutterlaugen' },
  { value: '07 06 07', viewValue: 'halogenierte Reaktions- und Destillationsrückstände' },
  { value: '07 06 08', viewValue: 'andere Reaktions- und Destillationsrückstände' },
  { value: '07 06 09', viewValue: 'halogenierte Filterkuchen, gebrauchte Aufsaugmaterialien' },
  { value: '07 06 10', viewValue: 'andere Filterkuchen, gebrauchte Aufsaugmaterialien' },
  { value: '07 06 11', viewValue: 'Schlämme aus der betriebseigenen Abwasserbehandlung, die gefährliche Stoffe enthalten' },
  { value: '07 06 12', viewValue: 'Schlämme aus der betriebseigenen Abwasserbehandlung mit Ausnahme derjenigen, die unter 07 06 11 fallen' },
  { value: '07 06 99', viewValue: 'Abfälle a. n. g.' },
  { value: '07 07 01', viewValue: 'wässrige Waschflüssigkeiten und Mutterlaugen' },
  { value: '07 07 03', viewValue: 'halogenorganische Lösemittel, Waschflüssigkeiten und Mutterlaugen' },
  { value: '07 07 04', viewValue: 'andere organische Lösemittel, Waschflüssigkeiten und Mutterlaugen' },
  { value: '07 07 07', viewValue: 'halogenierte Reaktions- und Destillationsrückstände' },
  { value: '07 07 08', viewValue: 'andere Reaktions- und Destillationsrückstände' },
  { value: '07 07 09', viewValue: 'halogenierte Filterkuchen, gebrauchte Aufsaugmaterialien' },
  { value: '07 07 10', viewValue: 'andere Filterkuchen, gebrauchte Aufsaugmaterialien' },
  { value: '07 07 11', viewValue: 'Schlämme aus der betriebseigenen Abwasserbehandlung, die gefährliche Stoffe enthalten' },
  { value: '07 07 12', viewValue: 'Schlämme aus der betriebseigenen Abwasserbehandlung mit Ausnahme derjenigen, die unter 07 07 11 fallen' },
  { value: '07 07 99', viewValue: 'Abfälle a. n. g.' },
    { value: '08 01 11', viewValue: 'Farb- und Lackabfälle, die organische Lösemittel oder andere gefährliche Stoffe enthalten' },
  { value: '08 01 12', viewValue: 'Farb- und Lackabfälle mit Ausnahme derjenigen, die unter 08 01 11 fallen' },
  { value: '08 01 13', viewValue: 'Farb- und Lackschlämme, die organische Lösemittel oder andere gefährliche Stoffe enthalten' },
  { value: '08 01 14', viewValue: 'Farb- und Lackschlämme mit Ausnahme derjenigen, die unter 08 01 13 fallen' },
  { value: '08 01 15', viewValue: 'wässrige Schlämme, die Farben oder Lacke mit organischen Lösemitteln oder anderen gefährlichen Stoffen enthalten' },
  { value: '08 01 16', viewValue: 'wässrige Schlämme, die Farben oder Lacke enthalten, mit Ausnahme derjenigen, die unter 08 01 15 fallen' },
  { value: '08 01 17', viewValue: 'Abfälle aus der Farb- oder Lackentfernung, die organische Lösemittel oder andere gefährliche Stoffe enthalten' },
  { value: '08 01 18', viewValue: 'Abfälle aus der Farb- oder Lackentfernung mit Ausnahme derjenigen, die unter 08 01 17 fallen' },
  { value: '08 01 19', viewValue: 'wässrige Suspensionen, die Farben oder Lacke mit organischen Lösemitteln oder anderen gefährlichen Stoffen enthalten' },
  { value: '08 01 20', viewValue: 'wässrige Suspensionen, die Farben oder Lacke enthalten, mit Ausnahme derjenigen, die unter 08 01 19 fallen' },
  { value: '08 01 21', viewValue: 'Farb- oder Lackentfernerabfälle' },
  { value: '08 01 99', viewValue: 'Abfälle a. n. g.' },
  { value: '08 02 01', viewValue: 'Abfälle von Beschichtungspulver' },
  { value: '08 02 02', viewValue: 'wässrige Schlämme, die keramische Werkstoffe enthalten' },
  { value: '08 02 03', viewValue: 'wässrige Suspensionen, die keramische Werkstoffe enthalten' },
  { value: '08 02 99', viewValue: 'Abfälle a. n. g.' },
  { value: '08 03 07', viewValue: 'wässrige Schlämme, die Druckfarben enthalten' },
  { value: '08 03 08', viewValue: 'wässrige flüssige Abfälle, die Druckfarben enthalten' },
  { value: '08 03 12', viewValue: 'Druckfarbenabfälle, die gefährliche Stoffe enthalten' },
  { value: '08 03 13', viewValue: 'Druckfarbenabfälle mit Ausnahme derjenigen, die unter 08 03 12 fallen' },
  { value: '08 03 14', viewValue: 'Druckfarbenschlämme, die gefährliche Stoffe enthalten' },
  { value: '08 03 15', viewValue: 'Druckfarbenschlämme mit Ausnahme derjenigen, die unter 08 03 14 fallen' },
  { value: '08 03 16', viewValue: 'Abfälle von Ätzlösungen' },
  { value: '08 03 17', viewValue: 'Tonerabfälle, die gefährliche Stoffe enthalten' },
  { value: '08 03 18', viewValue: 'Tonerabfälle mit Ausnahme derjenigen, die unter 08 03 17 fallen' },
  { value: '08 03 19', viewValue: 'Dispersionsöl' },
  { value: '08 03 99', viewValue: 'Abfälle a. n. g.' },
  { value: '08 04 09', viewValue: 'Klebstoff- und Dichtmassenabfälle, die organische Lösemittel oder andere gefährliche Stoffe enthalten' },
  { value: '08 04 10', viewValue: 'Klebstoff- und Dichtmassenabfälle mit Ausnahme derjenigen, die unter 08 04 09 fallen' },
  { value: '08 04 11', viewValue: 'klebstoff- und dichtmassenhaltige Schlämme, die organische Lösemittel oder andere gefährliche Stoffe enthalten' },
  { value: '08 04 12', viewValue: 'klebstoff- und dichtmassenhaltige Schlämme mit Ausnahme derjenigen, die unter 08 04 11 fallen' },
  { value: '08 04 13', viewValue: 'wässrige Schlämme, die Klebstoffe oder Dichtmassen mit organischen Lösemitteln oder anderen gefährlichen Stoffen enthalten' },
  { value: '08 04 14', viewValue: 'wässrige Schlämme, die Klebstoffe oder Dichtmassen enthalten, mit Ausnahme derjenigen, die unter 08 04 13 fallen' },
  { value: '08 04 15', viewValue: 'wässrige flüssige Abfälle, die Klebstoffe oder Dichtmassen mit organischen Lösemitteln oder anderen gefährlichen Stoffen enthalten' },
  { value: '08 04 16', viewValue: 'wässrige flüssige Abfälle, die Klebstoffe oder Dichtmassen enthalten, mit Ausnahme derjenigen, die unter 08 04 15 fallen' },
  { value: '08 04 17', viewValue: 'Harzöle' },
  { value: '08 04 99', viewValue: 'Abfälle a. n. g.' },
  { value: '08 05 01', viewValue: 'Isocyanatabfälle' },
  { value: '09 01 01', viewValue: 'Entwickler und Aktivatorenlösungen auf Wasserbasis' },
  { value: '09 01 02', viewValue: 'Offsetdruckplatten-Entwicklerlösungen auf Wasserbasis' },
  { value: '09 01 03', viewValue: 'Entwicklerlösungen auf Lösemittelbasis' },
  { value: '09 01 04', viewValue: 'Fixierbäder' },
  { value: '09 01 05', viewValue: 'Bleichlösungen und Bleich-Fixier-Bäder' },
  { value: '09 01 06', viewValue: 'silberhaltige Abfälle aus der betriebseigenen Behandlung fotografischer Abfälle' },
  { value: '09 01 07', viewValue: 'Filme und fotografische Papiere, die Silber oder Silberverbindungen enthalten' },
  { value: '09 01 08', viewValue: 'Filme und fotografische Papiere, die kein Silber und keine Silberverbindungen enthalten' },
  { value: '09 01 10', viewValue: 'Einwegkameras ohne Batterien' },
  { value: '09 01 11', viewValue: 'Einwegkameras mit Batterien, die unter 16 06 01, 16 06 02 oder 16 06 03 fallen' },
  { value: '09 01 12', viewValue: 'Einwegkameras mit Batterien mit Ausnahme derjenigen, die unter 09 01 11 fallen' },
  { value: '09 01 13', viewValue: 'wässrige flüssige Abfälle aus der betriebseigenen Silberrückgewinnung mit Ausnahme derjenigen, die unter 09 01 06 fallen' },
  { value: '09 01 99', viewValue: 'Abfälle a. n. g.' },
    { value: '10 01 01', viewValue: 'Rost- und Kesselasche, Schlacken und Kesselstaub mit Ausnahme von Kesselstaub, der unter 10 01 04 fällt' },
  { value: '10 01 02', viewValue: 'Filterstäube aus Kohlefeuerung' },
  { value: '10 01 03', viewValue: 'Filterstäube aus Torffeuerung und Feuerung mit (unbehandeltem) Holz' },
  { value: '10 01 04*', viewValue: 'Filterstäube und Kesselstaub aus Ölfeuerung' },
  { value: '10 01 05', viewValue: 'Reaktionsabfälle auf Calciumbasis aus der Rauchgasentschwefelung in fester Form' },
  { value: '10 01 07', viewValue: 'Reaktionsabfälle auf Calciumbasis aus der Rauchgasentschwefelung in Form von Schlämmen' },
  { value: '10 01 09*', viewValue: 'Schwefelsäure' },
  { value: '10 01 13*', viewValue: 'Filterstäube aus emulgierten, als Brennstoffe verwendeten Kohlenwasserstoffen' },
  { value: '10 01 14*', viewValue: 'Rost- und Kesselasche, Schlacken und Kesselstaub aus der Abfallmitverbrennung, die gefährliche Stoffe enthalten' },
  { value: '10 01 15', viewValue: 'Rost- und Kesselasche, Schlacken und Kesselstaub aus der Abfallmitverbrennung mit Ausnahme derjenigen, die unter 10 01 14 fallen' },
  { value: '10 01 16*', viewValue: 'Filterstäube aus der Abfallmitverbrennung, die gefährliche Stoffe enthalten' },
  { value: '10 01 17', viewValue: 'Filterstäube aus der Abfallmitverbrennung mit Ausnahme derjenigen, die unter 10 01 16 fallen' },
  { value: '10 01 18*', viewValue: 'Abfälle aus der Abgasbehandlung, die gefährliche Stoffe enthalten' },
  { value: '10 01 19', viewValue: 'Abfälle aus der Abgasbehandlung mit Ausnahme derjenigen, die unter 10 01 05, 10 01 07 und 10 01 18 fallen' },
  { value: '10 01 20*', viewValue: 'Schlämme aus der betriebseigenen Abwasserbehandlung, die gefährliche Stoffe enthalten' },
  { value: '10 01 21', viewValue: 'Schlämme aus der betriebseigenen Abwasserbehandlung mit Ausnahme derjenigen, die unter 10 01 20 fallen' },
  { value: '10 01 22*', viewValue: 'wässrige Schlämme aus der Kesselreinigung, die gefährliche Stoffe enthalten' },
  { value: '10 01 23', viewValue: 'wässrige Schlämme aus der Kesselreinigung mit Ausnahme derjenigen, die unter 10 01 22 fallen' },
  { value: '10 01 24', viewValue: 'Sande aus der Wirbelschichtfeuerung' },
  { value: '10 01 25', viewValue: 'Abfälle aus der Lagerung und Vorbereitung von Brennstoffen für Kohlekraftwerke' },
  { value: '10 01 26', viewValue: 'Abfälle aus der Kühlwasserbehandlung' },
  { value: '10 01 99', viewValue: 'Abfälle a. n. g.' },
  { value: '10 02 01', viewValue: 'Abfälle aus der Verarbeitung von Schlacke' },
  { value: '10 02 02', viewValue: 'unbearbeitete Schlacke' },
  { value: '10 02 07*', viewValue: 'feste Abfälle aus der Abgasbehandlung, die gefährliche Stoffe enthalten' },
  { value: '10 02 08', viewValue: 'feste Abfälle aus der Abgasbehandlung mit Ausnahme derjenigen, die unter 10 02 07 fallen' },
  { value: '10 02 10', viewValue: 'Walzzunder' },
  { value: '10 02 11*', viewValue: 'ölhaltige Abfälle aus der Kühlwasserbehandlung' },
  { value: '10 02 12', viewValue: 'Abfälle aus der Kühlwasserbehandlung mit Ausnahme derjenigen, die unter 10 02 11 fallen' },
  { value: '10 02 13*', viewValue: 'Schlämme und Filterkuchen aus der Abgasbehandlung, die gefährliche Stoffe enthalten' },
  { value: '10 02 14', viewValue: 'Schlämme und Filterkuchen aus der Abgasbehandlung mit Ausnahme derjenigen, die unter 10 02 13 fallen' },
  { value: '10 02 15', viewValue: 'andere Schlämme und Filterkuchen' },
  { value: '10 02 99', viewValue: 'Abfälle a. n. g.' },
  { value: '10 03 02', viewValue: 'Anodenschrott' },
  { value: '10 03 04*', viewValue: 'Schlacken aus der Erstschmelze' },
  { value: '10 03 05', viewValue: 'Aluminiumoxidabfälle' },
  { value: '10 03 08*', viewValue: 'Salzschlacken aus der Zweitschmelze' },
  { value: '10 03 09*', viewValue: 'schwarze Krätzen aus der Zweitschmelze' },
  { value: '10 03 15*', viewValue: 'Abschaum, der entzündlich ist oder in Kontakt mit Wasser entzündliche Gase in gefährlicher Menge abgibt' },
  { value: '10 03 16', viewValue: 'Abschaum mit Ausnahme desjenigen, der unter 10 03 15 fällt' },
  { value: '10 03 17*', viewValue: 'teerhaltige Abfälle aus der Anodenherstellung' },
  { value: '10 03 18', viewValue: 'Abfälle aus der Anodenherstellung, die Kohlenstoff enthalten, mit Ausnahme derjenigen, die unter 10 03 17 fallen' },
  { value: '10 03 19*', viewValue: 'Filterstaub, der gefährliche Stoffe enthält' },
  { value: '10 03 20', viewValue: 'Filterstaub mit Ausnahme von Filterstaub, der unter 10 03 19 fällt' },
  { value: '10 03 21*', viewValue: 'andere Teilchen und Staub (einschließlich Kugelmühlenstaub), die gefährliche Stoffe enthalten' },
  { value: '10 03 22', viewValue: 'andere Teilchen und Staub (einschließlich Kugelmühlenstaub) mit Ausnahme derjenigen, die unter 10 03 21 fallen' },
  { value: '10 03 23*', viewValue: 'feste Abfälle aus der Abgasbehandlung, die gefährliche Stoffe enthalten' },
  { value: '10 03 24', viewValue: 'feste Abfälle aus der Abgasbehandlung mit Ausnahme derjenigen, die unter 10 03 23 fallen' },
  { value: '10 03 25*', viewValue: 'Schlämme und Filterkuchen aus der Abgasbehandlung, die gefährliche Stoffe enthalten' },
  { value: '10 03 26', viewValue: 'Schlämme und Filterkuchen aus der Abgasbehandlung mit Ausnahme derjenigen, die unter 10 03 25 fallen' },
  { value: '10 03 27*', viewValue: 'ölhaltige Abfälle aus der Kühlwasserbehandlung' },
  { value: '10 03 28', viewValue: 'Abfälle aus der Kühlwasserbehandlung mit Ausnahme derjenigen, die unter 10 03 27 fallen' },
  { value: '10 03 29*', viewValue: 'gefährliche Stoffe enthaltende Abfälle aus der Behandlung von Salzschlacken und schwarzen Krätzen' },
  { value: '10 03 30', viewValue: 'Abfälle aus der Behandlung von Salzschlacken und schwarzen Krätzen mit Ausnahme derjenigen, die unter 10 03 29 fallen' },
  { value: '10 03 99', viewValue: 'Abfälle a. n. g.' },
  { value: '10 04 01*', viewValue: 'Schlacken (Erst- und Zweitschmelze)' },
  { value: '10 04 02*', viewValue: 'Krätzen und Abschaum (Erst- und Zweitschmelze)' },
  { value: '10 04 03*', viewValue: 'Calciumarsenat' },
  { value: '10 04 04*', viewValue: 'Filterstaub' },
  { value: '10 04 05*', viewValue: 'andere Teilchen und Staub' },
  { value: '10 04 06*', viewValue: 'feste Abfälle aus der Abgasbehandlung' },
  { value: '10 04 07*', viewValue: 'Schlämme und Filterkuchen aus der Abgasbehandlung' },
  { value: '10 04 09*', viewValue: 'ölhaltige Abfälle aus der Kühlwasserbehandlung' },
  { value: '10 04 10', viewValue: 'Abfälle aus der Kühlwasserbehandlung mit Ausnahme derjenigen, die unter 10 04 09 fallen' },
  { value: '10 04 99', viewValue: 'Abfälle a. n. g.' },
  { value: '10 05 01', viewValue: 'Schlacken (Erst- und Zweitschmelze)' },
  { value: '10 05 03*', viewValue: 'Filterstaub' },
  { value: '10 05 04', viewValue: 'andere Teilchen und Staub' },
  { value: '10 05 05*', viewValue: 'feste Abfälle aus der Abgasbehandlung' },
  { value: '10 05 06*', viewValue: 'Schlämme und Filterkuchen aus der Abgasbehandlung' },
  { value: '10 05 08*', viewValue: 'ölhaltige Abfälle aus der Kühlwasserbehandlung' },
  { value: '10 05 09', viewValue: 'Abfälle aus der Kühlwasserbehandlung mit Ausnahme derjenigen, die unter 10 05 08 fallen' },
  { value: '10 05 10*', viewValue: 'Krätzen und Abschaum, die entzündlich sind oder in Kontakt mit Wasser entzündliche Gase in gefährlicher Menge abgeben' },
  { value: '10 05 11', viewValue: 'Krätzen und Abschaum mit Ausnahme derjenigen, die unter 10 05 10 fallen' },
  { value: '10 05 99', viewValue: 'Abfälle a. n. g.' },
  { value: '10 06 01', viewValue: 'Schlacken (Erst- und Zweitschmelze)' },
  { value: '10 06 02', viewValue: 'Krätzen und Abschaum (Erst- und Zweitschmelze)' },
  { value: '10 06 03*', viewValue: 'Filterstaub' },
  { value: '10 06 04', viewValue: 'andere Teilchen und Staub' },
  { value: '10 06 06*', viewValue: 'feste Abfälle aus der Abgasbehandlung' },
  { value: '10 06 07*', viewValue: 'Schlämme und Filterkuchen aus der Abgasbehandlung' },
  { value: '10 06 09*', viewValue: 'ölhaltige Abfälle aus der Kühlwasserbehandlung' },
  { value: '10 06 10', viewValue: 'Abfälle aus der Kühlwasserbehandlung mit Ausnahme derjenigen, die unter 10 06 09 fallen' },
  { value: '10 06 99', viewValue: 'Abfälle a. n. g.' },
  { value: '10 07 01', viewValue: 'Schlacken (Erst- und Zweitschmelze)' },
  { value: '10 07 02', viewValue: 'Krätzen und Abschaum (Erst- und Zweitschmelze)' },
  { value: '10 07 03', viewValue: 'feste Abfälle aus der Abgasbehandlung' },
  { value: '10 07 04', viewValue: 'andere Teilchen und Staub' },
  { value: '10 07 05', viewValue: 'Schlämme und Filterkuchen aus der Abgasbehandlung' },
  { value: '10 07 07*', viewValue: 'ölhaltige Abfälle aus der Kühlwasserbehandlung' },
  { value: '10 07 08', viewValue: 'Abfälle aus der Kühlwasserbehandlung mit Ausnahme derjenigen, die unter 10 07 07 fallen' },
  { value: '10 07 99', viewValue: 'Abfälle a. n. g.' },
  { value: '10 08 04', viewValue: 'Teilchen und Staub' },
  { value: '10 08 08*', viewValue: 'Salzschlacken (Erst- und Zweitschmelze)' },
  { value: '10 08 09', viewValue: 'andere Schlacken' },
  { value: '10 08 10*', viewValue: 'Krätzen und Abschaum, die entzündlich sind oder in Kontakt mit Wasser entzündliche Gase in gefährlicher Menge abgeben' },
  { value: '10 08 11', viewValue: 'Krätzen und Abschaum mit Ausnahme derjenigen, die unter 10 08 10 fallen' },
  { value: '10 08 12*', viewValue: 'teerhaltige Abfälle aus der Anodenherstellung' },
  { value: '10 08 13', viewValue: 'Abfälle aus der Anodenherstellung, die Kohlenstoff enthalten, mit Ausnahme derjenigen, die unter 10 08 12 fallen' },
  { value: '10 08 14', viewValue: 'Anodenschrott' },
  { value: '10 08 15*', viewValue: 'Filterstaub, der gefährliche Stoffe enthält' },
  { value: '10 08 16', viewValue: 'Filterstaub mit Ausnahme desjenigen, der unter 10 08 15 fällt' },
  { value: '10 08 17*', viewValue: 'Schlämme und Filterkuchen aus der Abgasbehandlung, die gefährliche Stoffe enthalten' },
  { value: '10 08 18', viewValue: 'Schlämme und Filterkuchen aus der Abgasbehandlung mit Ausnahme derjenigen, die unter 10 08 17 fallen' },
  { value: '10 08 19*', viewValue: 'ölhaltige Abfälle aus der Kühlwasserbehandlung' },
  { value: '10 08 20', viewValue: 'Abfälle aus der Kühlwasserbehandlung mit Ausnahme derjenigen, die unter 10 08 19 fallen' },
  { value: '10 08 99', viewValue: 'Abfälle a. n. g.' },
  { value: '10 09 03', viewValue: 'Ofenschlacke' },
  { value: '10 09 05*', viewValue: 'gefährliche Stoffe enthaltende Gießformen und -sande vor dem Gießen' },
  { value: '10 09 06', viewValue: 'Gießformen und -sande vor dem Gießen mit Ausnahme derjenigen, die unter 10 09 05 fallen' },
  { value: '10 09 07*', viewValue: 'gefährliche Stoffe enthaltende Gießformen und -sande nach dem Gießen' },
  { value: '10 09 08', viewValue: 'Gießformen und -sande nach dem Gießen mit Ausnahme derjenigen, die unter 10 09 07 fallen' },
  { value: '10 09 09*', viewValue: 'Filterstaub, der gefährliche Stoffe enthält' },
  { value: '10 09 10', viewValue: 'Filterstaub mit Ausnahme desjenigen, der unter 10 09 09 fällt' },
  { value: '10 09 11*', viewValue: 'andere Teilchen, die gefährliche Stoffe enthalten' },
  { value: '10 09 12', viewValue: 'andere Teilchen mit Ausnahme derjenigen, die unter 10 09 11 fallen' },
  { value: '10 09 13*', viewValue: 'Abfälle von Bindemitteln, die gefährliche Stoffe enthalten' },
  { value: '10 09 14', viewValue: 'Abfälle von Bindemitteln mit Ausnahme derjenigen, die unter 10 09 13 fallen' },
  { value: '10 09 15*', viewValue: 'Abfälle aus rissanzeigenden Substanzen, die gefährliche Stoffe enthalten' },
  { value: '10 09 16', viewValue: 'Abfälle aus rissanzeigenden Substanzen mit Ausnahme derjenigen, die unter 10 09 15 fallen' },
  { value: '10 09 99', viewValue: 'Abfälle a. n. g.' },
  { value: '10 10 03', viewValue: 'Ofenschlacke' },
  { value: '10 10 05*', viewValue: 'gefährliche Stoffe enthaltende Gießformen und -sande vor dem Gießen' },
  { value: '10 10 06', viewValue: 'Gießformen und -sande vor dem Gießen mit Ausnahme derjenigen, die unter 10 10 05 fallen' },
  { value: '10 10 07*', viewValue: 'gefährliche Stoffe enthaltende Gießformen und -sande nach dem Gießen' },
  { value: '10 10 08', viewValue: 'Gießformen und -sande nach dem Gießen mit Ausnahme derjenigen, die unter 10 10 07 fallen' },
  { value: '10 10 09*', viewValue: 'Filterstaub, der gefährliche Stoffe enthält' },
  { value: '10 10 10', viewValue: 'Filterstaub mit Ausnahme desjenigen, der unter 10 10 09 fällt' },
  { value: '10 10 11*', viewValue: 'andere Teilchen, die gefährliche Stoffe enthalten' },
  { value: '10 10 12', viewValue: 'andere Teilchen mit Ausnahme derjenigen, die unter 10 10 11 fallen' },
  { value: '10 10 13*', viewValue: 'Abfälle von Bindemitteln, die gefährliche Stoffe enthalten' },
  { value: '10 10 14', viewValue: 'Abfälle von Bindemitteln mit Ausnahme derjenigen, die unter 10 10 13 fallen' },
  { value: '10 10 15*', viewValue: 'Abfälle aus rissanzeigenden Substanzen, die gefährliche Stoffe enthalten' },
  { value: '10 10 16', viewValue: 'Abfälle aus rissanzeigenden Substanzen mit Ausnahme derjenigen, die unter 10 10 15 fallen' },
  { value: '10 10 99', viewValue: 'Abfälle a. n. g.' },
  { value: '10 11 03', viewValue: 'Glasfaserabfall' },
  { value: '10 11 05', viewValue: 'Teilchen und Staub' },
  { value: '10 11 09*', viewValue: 'Gemengeabfall mit gefährlichen Stoffen vor dem Schmelzen' },
  { value: '10 11 10', viewValue: 'Gemengeabfall vor dem Schmelzen mit Ausnahme desjenigen, der unter 10 11 09 fällt' },
  { value: '10 11 11*', viewValue: 'Glasabfall in kleinen Teilchen und Glasstaub, die Schwermetalle enthalten (z.B. aus Kathodenstrahlröhren)' },
  { value: '10 11 12', viewValue: 'Glasabfall mit Ausnahme desjenigen, der unter 10 11 11 fällt' },
  { value: '10 11 13*', viewValue: 'Glaspolier- und Glasschleifschlämme, die gefährliche Stoffe enthalten' },
  { value: '10 11 14', viewValue: 'Glaspolier- und Glasschleifschlämme mit Ausnahme derjenigen, die unter 10 11 13 fallen' },
  { value: '10 11 15*', viewValue: 'feste Abfälle aus der Abgasbehandlung, die gefährliche Stoffe enthalten' },
  { value: '10 11 16', viewValue: 'feste Abfälle aus der Abgasbehandlung mit Ausnahme derjenigen, die unter 10 11 15 fallen' },
  { value: '10 11 17*', viewValue: 'Schlämme und Filterkuchen aus der Abgasbehandlung, die gefährliche Stoffe enthalten' },
  { value: '10 11 18', viewValue: 'Schlämme und Filterkuchen aus der Abgasbehandlung mit Ausnahme derjenigen, die unter 10 11 17 fallen' },
  { value: '10 11 19*', viewValue: 'feste Abfälle aus der betriebseigenen Abwasserbehandlung, die gefährliche Stoffe enthalten' },
  { value: '10 11 20', viewValue: 'feste Abfälle aus der betriebseigenen Abwasserbehandlung mit Ausnahme derjenigen, die unter 10 11 19 fallen' },
  { value: '10 11 99', viewValue: 'Abfälle a. n. g.' },
  { value: '10 12 01', viewValue: 'Rohmischungen vor dem Brennen' },
  { value: '10 12 03', viewValue: 'Teilchen und Staub' },
  { value: '10 12 05', viewValue: 'Schlämme und Filterkuchen aus der Abgasbehandlung' },
  { value: '10 12 06', viewValue: 'verworfene Formen' },
  { value: '10 12 08', viewValue: 'Abfälle aus Keramikerzeugnissen, Ziegeln, Fliesen und Steinzeug (nach dem Brennen)' },
  { value: '10 12 09*', viewValue: 'feste Abfälle aus der Abgasbehandlung, die gefährliche Stoffe enthalten' },
  { value: '10 12 10', viewValue: 'feste Abfälle aus der Abgasbehandlung mit Ausnahme derjenigen, die unter 10 12 09 fallen' },
  { value: '10 12 11*', viewValue: 'Glasurabfälle, die Schwermetalle enthalten' },
  { value: '10 12 12', viewValue: 'Glasurabfälle mit Ausnahme derjenigen, die unter 10 12 11 fallen' },
  { value: '10 12 13', viewValue: 'Schlämme aus der betriebseigenen Abwasserbehandlung' },
  { value: '10 12 99', viewValue: 'Abfälle a. n. g.' },
  { value: '10 13 01', viewValue: 'Abfälle von Rohgemenge vor dem Brennen' },
  { value: '10 13 04', viewValue: 'Abfälle aus der Kalzinierung und Hydratisierung von Branntkalk' },
  { value: '10 13 06', viewValue: 'Teilchen und Staub (außer 10 13 12 und 10 13 13)' },
  { value: '10 13 07', viewValue: 'Schlämme und Filterkuchen aus der Abgasbehandlung' },
  { value: '10 13 09*', viewValue: 'asbesthaltige Abfälle aus der Herstellung von Asbestzement' },
  { value: '10 13 10', viewValue: 'Abfälle aus der Herstellung von Asbestzement mit Ausnahme derjenigen, die unter 10 13 09 fallen' },
  { value: '10 13 11', viewValue: 'Abfälle aus der Herstellung anderer Verbundstoffe auf Zementbasis mit Ausnahme derjenigen, die unter 10 13 09 und 10 13 10 fallen' },
  { value: '10 13 12*', viewValue: 'feste Abfälle aus der Abgasbehandlung, die gefährliche Stoffe enthalten' },
  { value: '10 13 13', viewValue: 'feste Abfälle aus der Abgasbehandlung mit Ausnahme derjenigen, die unter 10 13 12 fallen' },
  { value: '10 13 14', viewValue: 'Betonabfälle und Betonschlämme' },
  { value: '10 13 99', viewValue: 'Abfälle a. n. g.' },
  { value: '10 14 01*', viewValue: 'quecksilberhaltige Abfälle aus der Gasreinigung' },
  { value: '11 01 05*', viewValue: 'saure Beizlösungen' },
  { value: '11 01 06*', viewValue: 'Säuren a. n. g.' },
  { value: '11 01 07*', viewValue: 'alkalische Beizlösungen' },
  { value: '11 01 08*', viewValue: 'Phosphatierschlämme' },
  { value: '11 01 09*', viewValue: 'Schlämme und Filterkuchen, die gefährliche Stoffe enthalten' },
  { value: '11 01 10', viewValue: 'Schlämme und Filterkuchen mit Ausnahme derjenigen, die unter 11 01 09 fallen' },
  { value: '11 01 11*', viewValue: 'wässrige Spülflüssigkeiten, die gefährliche Stoffe enthalten' },
  { value: '11 01 12', viewValue: 'wässrige Spülflüssigkeiten mit Ausnahme derjenigen, die unter 11 01 11 fallen' },
  { value: '11 01 13*', viewValue: 'Abfälle aus der Entfettung, die gefährliche Stoffe enthalten' },
  { value: '11 01 14', viewValue: 'Abfälle aus der Entfettung mit Ausnahme derjenigen, die unter 11 01 13 fallen' },
  { value: '11 01 15*', viewValue: 'Eluate und Schlämme aus Membransystemen oder Ionenaustauschsystemen, die gefährliche Stoffe enthalten' },
  { value: '11 01 16*', viewValue: 'gesättigte oder verbrauchte Ionenaustauscherharze' },
  { value: '11 01 98*', viewValue: 'andere Abfälle, die gefährliche Stoffe enthalten' },
  { value: '11 01 99', viewValue: 'Abfälle a. n. g.' },
  { value: '11 02 02*', viewValue: 'Schlämme aus der Zink-Hydrometallurgie (einschließlich Jarosit, Goethit)' },
  { value: '11 02 03', viewValue: 'Abfälle aus der Herstellung von Anoden für wässrige elektrolytische Prozesse' },
  { value: '11 02 05*', viewValue: 'Abfälle aus Prozessen der Kupfer-Hydrometallurgie, die gefährliche Stoffe enthalten' },
  { value: '11 02 06', viewValue: 'Abfälle aus Prozessen der Kupfer-Hydrometallurgie mit Ausnahme derjenigen, die unter 11 02 05 fallen' },
  { value: '11 02 07*', viewValue: 'andere Abfälle, die gefährliche Stoffe enthalten' },
  { value: '11 02 99', viewValue: 'Abfälle a. n. g.' },
  { value: '11 03 01*', viewValue: 'cyanidhaltige Abfälle' },
  { value: '11 03 02*', viewValue: 'andere Abfälle' },
  { value: '11 05 01', viewValue: 'Hartzink' },
  { value: '11 05 02', viewValue: 'Zinkasche' },
  { value: '11 05 03*', viewValue: 'feste Abfälle aus der Abgasbehandlung' },
  { value: '11 05 04*', viewValue: 'gebrauchte Flussmittel' },
  { value: '11 05 99', viewValue: 'Abfälle a. n. g.' },
  { value: '12 01 01', viewValue: 'Eisenfeil- und -drehspäne' },
  { value: '12 01 02', viewValue: 'Eisenstaub und -teilchen' },
  { value: '12 01 03', viewValue: 'NE-Metallfeil- und -drehspäne' },
  { value: '12 01 04', viewValue: 'NE-Metallstaub und -teilchen' },
  { value: '12 01 05', viewValue: 'Kunststoffspäne und -drehspäne' },
  { value: '12 01 06*', viewValue: 'halogenhaltige Bearbeitungsöle auf Mineralölbasis (außer Emulsionen und Lösungen)' },
  { value: '12 01 07*', viewValue: 'halogenfreie Bearbeitungsöle auf Mineralölbasis (außer Emulsionen und Lösungen)' },
  { value: '12 01 08*', viewValue: 'halogenhaltige Bearbeitungsemulsionen und -lösungen' },
  { value: '12 01 09*', viewValue: 'halogenfreie Bearbeitungsemulsionen und -lösungen' },
  { value: '12 01 10*', viewValue: 'synthetische Bearbeitungsöle' },
  { value: '12 01 12*', viewValue: 'gebrauchte Wachse und Fette' },
  { value: '12 01 13', viewValue: 'Schweißabfälle' },
  { value: '12 01 14*', viewValue: 'Bearbeitungsschlämme, die gefährliche Stoffe enthalten' },
  { value: '12 01 15', viewValue: 'Bearbeitungsschlämme mit Ausnahme derjenigen, die unter 12 01 14 fallen' },
  { value: '12 01 16*', viewValue: 'Strahlmittelabfälle, die gefährliche Stoffe enthalten' },
  { value: '12 01 17', viewValue: 'Strahlmittelabfälle mit Ausnahme derjenigen, die unter 12 01 16 fallen' },
  { value: '12 01 18*', viewValue: 'ölhaltige Metallschlämme (Schleif-, Hon- und Läppschlämme)' },
  { value: '12 01 19*', viewValue: 'biologisch leicht abbaubare Bearbeitungsöle' },
  { value: '12 01 20*', viewValue: 'gebrauchte Hon- und Schleifmittel, die gefährliche Stoffe enthalten' },
  { value: '12 01 21', viewValue: 'gebrauchte Hon- und Schleifmittel mit Ausnahme derjenigen, die unter 12 01 20 fallen' },
  { value: '12 01 99', viewValue: 'Abfälle a. n. g.' },
  { value: '12 03 01*', viewValue: 'wässrige Waschflüssigkeiten' },
  { value: '12 03 02*', viewValue: 'Abfälle aus der Dampfentfettung' },
  { value: '13 01 01*', viewValue: 'Hydrauliköle, die PCB enthalten' },
  { value: '13 01 04*', viewValue: 'chlorierte Emulsionen' },
  { value: '13 01 05*', viewValue: 'nichtchlorierte Emulsionen' },
  { value: '13 01 09*', viewValue: 'chlorierte Hydrauliköle auf Mineralölbasis' },
  { value: '13 01 10*', viewValue: 'nichtchlorierte Hydrauliköle auf Mineralölbasis' },
  { value: '13 01 11*', viewValue: 'synthetische Hydrauliköle' },
  { value: '13 01 12*', viewValue: 'biologisch leicht abbaubare Hydrauliköle' },
  { value: '13 01 13*', viewValue: 'andere Hydrauliköle' },
  { value: '13 02 04*', viewValue: 'chlorierte Maschinen-, Getriebe- und Schmieröle auf Mineralölbasis' },
  { value: '13 02 05*', viewValue: 'nichtchlorierte Maschinen-, Getriebe- und Schmieröle auf Mineralölbasis' },
  { value: '13 02 06*', viewValue: 'synthetische Maschinen-, Getriebe- und Schmieröle' },
  { value: '13 02 07*', viewValue: 'biologisch leicht abbaubare Maschinen-, Getriebe- und Schmieröle' },
  { value: '13 02 08*', viewValue: 'andere Maschinen-, Getriebe- und Schmieröle' },
  { value: '13 03 01*', viewValue: 'Isolier- und Wärmeübertragungsöle, die PCB enthalten' },
  { value: '13 03 06*', viewValue: 'chlorierte Isolier- und Wärmeübertragungsöle auf Mineralölbasis mit Ausnahme derjenigen, die unter 13 03 01 fallen' },
  { value: '13 03 07*', viewValue: 'nichtchlorierte Isolier- und Wärmeübertragungsöle auf Mineralölbasis' },
  { value: '13 03 08*', viewValue: 'synthetische Isolier- und Wärmeübertragungsöle' },
  { value: '13 03 09*', viewValue: 'biologisch leicht abbaubare Isolier- und Wärmeübertragungsöle' },
  { value: '13 03 10*', viewValue: 'andere Isolier- und Wärmeübertragungsöle' },
  { value: '13 04 01*', viewValue: 'Bilgenöle aus der Binnenschifffahrt' },
  { value: '13 04 02*', viewValue: 'Bilgenöle aus Molenablaufkanälen' },
  { value: '13 04 03*', viewValue: 'Bilgenöle aus der übrigen Schifffahrt' },
  { value: '13 05 01*', viewValue: 'feste Abfälle aus Sandfanganlagen und Öl-/Wasserabscheidern' },
  { value: '13 05 02*', viewValue: 'Schlämme aus Öl-/Wasserabscheidern' },
  { value: '13 05 03*', viewValue: 'Schlämme aus Einlaufschächten' },
  { value: '13 05 06*', viewValue: 'Öle aus Öl-/Wasserabscheidern' },
  { value: '13 05 07*', viewValue: 'öliges Wasser aus Öl-/Wasserabscheidern' },
  { value: '13 05 08*', viewValue: 'Abfallgemische aus Sandfanganlagen und Öl-/Wasserabscheidern' },
  { value: '13 07 01*', viewValue: 'Heizöl und Diesel' },
  { value: '13 07 02*', viewValue: 'Benzin' },
  { value: '13 07 03*', viewValue: 'andere Brennstoffe (einschließlich Gemische)' },
  { value: '13 08 01*', viewValue: 'Schlämme oder Emulsionen aus Entsalzern' },
  { value: '13 08 02*', viewValue: 'andere Emulsionen' },
  { value: '13 08 99*', viewValue: 'Abfälle a. n. g.' },
  { value: '14 06 01*', viewValue: 'Fluorchlorkohlenwasserstoffe, HFCKW, HFKW' },
  { value: '14 06 02*', viewValue: 'andere halogenierte Lösemittel und Lösemittelgemische' },
  { value: '14 06 03*', viewValue: 'andere Lösemittel und Lösemittelgemische' },
  { value: '14 06 04*', viewValue: 'Schlämme oder feste Abfälle, die halogenierte Lösemittel enthalten' },
  { value: '14 06 05*', viewValue: 'Schlämme oder feste Abfälle, die andere Lösemittel enthalten' },
  { value: '15 01 01', viewValue: 'Verpackungen aus Papier und Pappe' },
  { value: '15 01 02', viewValue: 'Verpackungen aus Kunststoff' },
  { value: '15 01 03', viewValue: 'Verpackungen aus Holz' },
  { value: '15 01 04', viewValue: 'Verpackungen aus Metall' },
  { value: '15 01 05', viewValue: 'Verbundverpackungen' },
  { value: '15 01 06', viewValue: 'gemischte Verpackungen' },
  { value: '15 01 07', viewValue: 'Verpackungen aus Glas' },
  { value: '15 01 09', viewValue: 'Verpackungen aus Textilien' },
  { value: '15 01 10*', viewValue: 'Verpackungen, die Rückstände gefährlicher Stoffe enthalten oder durch gefährliche Stoffe verunreinigt sind' },
  { value: '15 01 11*', viewValue: 'Verpackungen aus Metall, die eine gefährliche feste poröse Matrix (z.B. Asbest) enthalten, einschließlich geleerter Druckbehältnisse' },
  { value: '15 02 02*', viewValue: 'Aufsaug- und Filtermaterialien (einschließlich Ölfilter a. n. g.), Wischtücher und Schutzkleidung, die durch gefährliche Stoffe verunreinigt sind' },
  { value: '15 02 03', viewValue: 'Aufsaug- und Filtermaterialien, Wischtücher und Schutzkleidung mit Ausnahme derjenigen, die unter 15 02 02 fallen' },
  { value: '16 01 03', viewValue: 'Altreifen' },
  { value: '16 01 04*', viewValue: 'Altfahrzeuge' },
  { value: '16 01 06', viewValue: 'Altfahrzeuge, die weder Flüssigkeiten noch andere gefährliche Bestandteile enthalten' },
  { value: '16 01 07*', viewValue: 'Ölfilter' },
  { value: '16 01 08*', viewValue: 'quecksilberhaltige Bauteile' },
  { value: '16 01 09*', viewValue: 'Bauteile, die PCB enthalten' },
  { value: '16 01 10*', viewValue: 'explosive Bauteile (z.B. aus Airbags)' },
  { value: '16 01 11*', viewValue: 'asbesthaltige Bremsbeläge' },
  { value: '16 01 12', viewValue: 'Bremsbeläge mit Ausnahme derjenigen, die unter 16 01 11 fallen' },
  { value: '16 01 13*', viewValue: 'Bremsflüssigkeiten' },
  { value: '16 01 14*', viewValue: 'Frostschutzmittel, die gefährliche Stoffe enthalten' },
  { value: '16 01 15', viewValue: 'Frostschutzmittel mit Ausnahme derjenigen, die unter 16 01 14 fallen' },
  { value: '16 01 16', viewValue: 'Flüssiggasbehälter' },
  { value: '16 01 17', viewValue: 'Eisenmetalle' },
  { value: '16 01 18', viewValue: 'Nichteisenmetalle' },
  { value: '16 01 19', viewValue: 'Kunststoffe' },
  { value: '16 01 20', viewValue: 'Glas' },
  { value: '16 01 21*', viewValue: 'gefährliche Bauteile mit Ausnahme derjenigen, die unter 16 01 07 bis 16 01 11, 16 01 13 und 16 01 14 fallen' },
  { value: '16 01 22', viewValue: 'Bauteile a.n.g.' },
  { value: '16 01 99', viewValue: 'Abfälle a. n. g.' },
  { value: '16 02 09*', viewValue: 'Transformatoren und Kondensatoren, die PCB enthalten' },
  { value: '16 02 10*', viewValue: 'gebrauchte Geräte, die PCB enthalten oder damit verunreinigt sind, mit Ausnahme derjenigen, die unter 16 02 09 fallen' },
  { value: '16 02 11*', viewValue: 'gebrauchte Geräte, die Fluorchlorkohlenwasserstoffe, HFCKW oder HFKW enthalten' },
  { value: '16 02 12*', viewValue: 'gebrauchte Geräte, die freies Asbest enthalten' },
  { value: '16 02 13*', viewValue: 'gefährliche Bauteile enthaltende gebrauchte Geräte mit Ausnahme derjenigen, die unter 16 02 09 bis 16 02 12 fallen' },
  { value: '16 02 14', viewValue: 'gebrauchte Geräte mit Ausnahme derjenigen, die unter 16 02 09 bis 16 02 13 fallen' },
  { value: '16 02 15*', viewValue: 'aus gebrauchten Geräten entfernte gefährliche Bauteile' },
  { value: '16 02 16', viewValue: 'aus gebrauchten Geräten entfernte Bauteile mit Ausnahme derjenigen, die unter 16 02 15 fallen' },
  { value: '16 03 03*', viewValue: 'anorganische Abfälle, die gefährliche Stoffe enthalten' },
  { value: '16 03 04', viewValue: 'anorganische Abfälle mit Ausnahme derjenigen, die unter 16 03 03 fallen' },
  { value: '16 03 05*', viewValue: 'organische Abfälle, die gefährliche Stoffe enthalten' },
  { value: '16 03 06', viewValue: 'organische Abfälle mit Ausnahme derjenigen, die unter 16 03 05 fallen' },
  { value: '16 03 07*', viewValue: 'metallisches Quecksilber' },
  { value: '16 04 01*', viewValue: 'Munitionsabfälle' },
  { value: '16 04 02*', viewValue: 'Feuerwerkskörperabfälle' },
  { value: '16 04 03*', viewValue: 'andere Explosivabfälle' },
  { value: '16 05 04*', viewValue: 'gefährliche Stoffe enthaltende Gase in Druckbehältern (einschließlich Halonen)' },
  { value: '16 05 05', viewValue: 'Gase in Druckbehältern mit Ausnahme derjenigen, die unter 16 05 04 fallen' },
  { value: '16 05 06*', viewValue: 'Laborchemikalien, die aus gefährlichen Stoffen bestehen oder solche enthalten, einschließlich Gemische von Laborchemikalien' },
  { value: '16 05 07*', viewValue: 'gebrauchte anorganische Chemikalien, die aus gefährlichen Stoffen bestehen oder solche enthalten' },
  { value: '16 05 08*', viewValue: 'gebrauchte organische Chemikalien, die aus gefährlichen Stoffen bestehen oder solche enthalten' },
  { value: '16 05 09', viewValue: 'gebrauchte Chemikalien mit Ausnahme derjenigen, die unter 16 05 06, 16 05 07 oder 16 05 08 fallen' },
  { value: '16 06 01*', viewValue: 'Bleibatterien' },
  { value: '16 06 02*', viewValue: 'Ni-Cd-Batterien' },
  { value: '16 06 03*', viewValue: 'Quecksilber enthaltende Batterien' },
  { value: '16 06 04', viewValue: 'Alkalibatterien (außer 16 06 03)' },
  { value: '16 06 05', viewValue: 'andere Batterien und Akkumulatoren' },
  { value: '16 06 06*', viewValue: 'getrennt gesammelte Elektrolyte aus Batterien und Akkumulatoren' },
  { value: '16 07 08*', viewValue: 'ölhaltige Abfälle' },
  { value: '16 07 09*', viewValue: 'Abfälle, die sonstige gefährliche Stoffe enthalten' },
  { value: '16 07 99', viewValue: 'Abfälle a. n. g.' },
  { value: '16 08 01', viewValue: 'gebrauchte Katalysatoren, die Gold, Silber, Rhenium, Rhodium, Palladium, Iridium oder Platin enthalten (außer 16 08 07)' },
  { value: '16 08 02*', viewValue: 'gebrauchte Katalysatoren, die gefährliche Übergangsmetalle oder deren Verbindungen enthalten' },
  { value: '16 08 03', viewValue: 'gebrauchte Katalysatoren, die Übergangsmetalle oder deren Verbindungen enthalten, a. n. g.' },
  { value: '16 08 04', viewValue: 'gebrauchte Katalysatoren von Crackprozessen (außer 16 08 07)' },
  { value: '16 08 05*', viewValue: 'gebrauchte Katalysatoren, die Phosphorsäure enthalten' },
  { value: '16 08 06*', viewValue: 'gebrauchte Flüssigkeiten, die als Katalysatoren verwendet wurden' },
  { value: '16 08 07*', viewValue: 'gebrauchte Katalysatoren, die durch gefährliche Stoffe verunreinigt sind' },
  { value: '16 09 01*', viewValue: 'Permanganate, z.B. Kaliumpermanganat' },
  { value: '16 09 02*', viewValue: 'Chromate, z.B. Kaliumchromat, Kalium- oder Natriumdichromat' },
  { value: '16 09 03*', viewValue: 'Peroxide, z.B. Wasserstoffperoxid' },
  { value: '16 09 04*', viewValue: 'oxidierende Stoffe a. n. g.' },
  { value: '16 10 01*', viewValue: 'wässrige flüssige Abfälle, die gefährliche Stoffe enthalten' },
  { value: '16 10 02', viewValue: 'wässrige flüssige Abfälle mit Ausnahme derjenigen, die unter 16 10 01 fallen' },
  { value: '16 10 03*', viewValue: 'wässrige Konzentrate, die gefährliche Stoffe enthalten' },
  { value: '16 10 04', viewValue: 'wässrige Konzentrate mit Ausnahme derjenigen, die unter 16 10 03 fallen' },
  { value: '16 11 01*', viewValue: 'Auskleidungen und feuerfeste Materialien auf Kohlenstoffbasis aus metallurgischen Prozessen, die gefährliche Stoffe enthalten' },
  { value: '16 11 02', viewValue: 'Auskleidungen und feuerfeste Materialien auf Kohlenstoffbasis aus metallurgischen Prozessen mit Ausnahme derjenigen, die unter 16 11 01 fallen' },
  { value: '16 11 03*', viewValue: 'andere Auskleidungen und feuerfeste Materialien aus metallurgischen Prozessen, die gefährliche Stoffe enthalten' },
  { value: '16 11 04', viewValue: 'andere Auskleidungen und feuerfeste Materialien aus metallurgischen Prozessen mit Ausnahme derjenigen, die unter 16 11 03 fallen' },
  { value: '16 11 05*', viewValue: 'Auskleidungen und feuerfeste Materialien aus nichtmetallurgischen Prozessen, die gefährliche Stoffe enthalten' },
  { value: '16 11 06', viewValue: 'Auskleidungen und feuerfeste Materialien aus nichtmetallurgischen Prozessen mit Ausnahme derjenigen, die unter 16 11 05 fallen' },
  { value: '17 01 01', viewValue: 'Beton' },
  { value: '17 01 02', viewValue: 'Ziegel' },
  { value: '17 01 03', viewValue: 'Fliesen und Keramik' },
  { value: '17 01 06*', viewValue: 'Gemische aus oder getrennte Fraktionen von Beton, Ziegeln, Fliesen und Keramik, die gefährliche Stoffe enthalten' },
  { value: '17 01 07', viewValue: 'Gemische aus Beton, Ziegeln, Fliesen und Keramik mit Ausnahme derjenigen, die unter 17 01 06 fallen' },
  { value: '17 02 01', viewValue: 'Holz' },
  { value: '17 02 02', viewValue: 'Glas' },
  { value: '17 02 03', viewValue: 'Kunststoff' },
  { value: '17 02 04*', viewValue: 'Glas, Kunststoff und Holz, die gefährliche Stoffe enthalten oder durch gefährliche Stoffe verunreinigt sind' },
  { value: '17 03 01*', viewValue: 'kohlenteerhaltige Bitumengemische' },
  { value: '17 03 02', viewValue: 'Bitumengemische mit Ausnahme derjenigen, die unter 17 03 01 fallen' },
  { value: '17 03 03*', viewValue: 'Kohlenteer und teerhaltige Produkte' },
  { value: '17 04 01', viewValue: 'Kupfer, Bronze, Messing' },
  { value: '17 04 02', viewValue: 'Aluminium' },
  { value: '17 04 03', viewValue: 'Blei' },
  { value: '17 04 04', viewValue: 'Zink' },
  { value: '17 04 05', viewValue: 'Eisen und Stahl' },
  { value: '17 04 06', viewValue: 'Zinn' },
  { value: '17 04 07', viewValue: 'gemischte Metalle' },
  { value: '17 04 09*', viewValue: 'Metallabfälle, die durch gefährliche Stoffe verunreinigt sind' },
  { value: '17 04 10*', viewValue: 'Kabel, die Öl, Kohlenteer oder andere gefährliche Stoffe enthalten' },
  { value: '17 04 11', viewValue: 'Kabel mit Ausnahme derjenigen, die unter 17 04 10 fallen' },
  { value: '17 05 03*', viewValue: 'Boden und Steine, die gefährliche Stoffe enthalten' },
  { value: '17 05 04', viewValue: 'Boden und Steine mit Ausnahme derjenigen, die unter 17 05 03 fallen' },
  { value: '17 05 05*', viewValue: 'Baggergut, das gefährliche Stoffe enthält' },
  { value: '17 05 06', viewValue: 'Baggergut mit Ausnahme desjenigen, das unter 17 05 05 fällt' },
  { value: '17 05 07*', viewValue: 'Gleisschotter, der gefährliche Stoffe enthält' },
  { value: '17 05 08', viewValue: 'Gleisschotter mit Ausnahme desjenigen, der unter 17 05 07 fällt' },
  { value: '17 06 01*', viewValue: 'Dämmmaterial, das Asbest enthält' },
  { value: '17 06 03*', viewValue: 'anderes Dämmmaterial, das aus gefährlichen Stoffen besteht oder solche Stoffe enthält' },
  { value: '17 06 04', viewValue: 'Dämmmaterial mit Ausnahme desjenigen, das unter 17 06 01 und 17 06 03 fällt' },
  { value: '17 06 05*', viewValue: 'asbesthaltige Baustoffe' },
  { value: '17 08 01*', viewValue: 'Baustoffe auf Gipsbasis, die durch gefährliche Stoffe verunreinigt sind' },
  { value: '17 08 02', viewValue: 'Baustoffe auf Gipsbasis mit Ausnahme derjenigen, die unter 17 08 01 fallen' },
  { value: '17 09 01*', viewValue: 'Bau- und Abbruchabfälle, die Quecksilber enthalten' },
  { value: '17 09 02*', viewValue: 'Bau- und Abbruchabfälle, die PCB enthalten (z.B. PCB-haltige Dichtungsmassen, PCB-haltige Bodenbeläge auf Harzbasis, PCB-haltige Isolierverglasungen, PCB-haltige Kondensatoren)' },
  { value: '17 09 03*', viewValue: 'sonstige Bau- und Abbruchabfälle (einschließlich gemischte Abfälle), die gefährliche Stoffe enthalten' },
  { value: '17 09 04', viewValue: 'gemischte Bau- und Abbruchabfälle mit Ausnahme derjenigen, die unter 17 09 01, 17 09 02 und 17 09 03 fallen' },
  { value: '18 01 01', viewValue: 'spitze oder scharfe Gegenstände (außer 18 01 03)' },
  { value: '18 01 02', viewValue: 'Körperteile und Organe, einschließlich Blutbeutel und Blutkonserven (außer 18 01 03)' },
  { value: '18 01 03*', viewValue: 'Abfälle, an deren Sammlung und Entsorgung aus infektionspräventiver Sicht besondere Anforderungen gestellt werden' },
  { value: '18 01 04', viewValue: 'Abfälle, an deren Sammlung und Entsorgung aus infektionspräventiver Sicht keine besonderen Anforderungen gestellt werden (z. B. Wund- und Gipsverbände, Wäsche, Einwegkleidung, Windeln)' },
  { value: '18 01 06*', viewValue: 'Chemikalien, die aus gefährlichen Stoffen bestehen oder solche enthalten' },
  { value: '18 01 07', viewValue: 'Chemikalien mit Ausnahme derjenigen, die unter 18 01 06 fallen' },
  { value: '18 01 08*', viewValue: 'zytotoxische und zytostatische Arzneimittel' },
  { value: '18 01 09', viewValue: 'Arzneimittel mit Ausnahme derjenigen, die unter 18 01 08 fallen' },
  { value: '18 01 10*', viewValue: 'Amalgamabfälle aus der Zahnmedizin' },
  { value: '18 02 01', viewValue: 'spitze oder scharfe Gegenstände mit Ausnahme derjenigen, die unter 18 02 02 fallen' },
  { value: '18 02 02*', viewValue: 'Abfälle, an deren Sammlung und Entsorgung aus infektionspräventiver Sicht besondere Anforderungen gestellt werden' },
  { value: '18 02 03', viewValue: 'Abfälle, an deren Sammlung und Entsorgung aus infektionspräventiver Sicht keine besonderen Anforderungen gestellt werden' },
  { value: '18 02 05*', viewValue: 'Chemikalien, die aus gefährlichen Stoffen bestehen oder solche enthalten' },
  { value: '18 02 06', viewValue: 'Chemikalien mit Ausnahme derjenigen, die unter 18 02 05 fallen' },
  { value: '18 02 07*', viewValue: 'zytotoxische und zytostatische Arzneimittel' },
  { value: '18 02 08', viewValue: 'Arzneimittel mit Ausnahme derjenigen, die unter 18 02 07 fallen' },
  { value: '19 01 02', viewValue: 'Eisenteile, aus der Rost- und Kesselasche entfernt' },
  { value: '19 01 05*', viewValue: 'Filterkuchen aus der Abgasbehandlung' },
  { value: '19 01 06*', viewValue: 'wässrige flüssige Abfälle aus der Abgasbehandlung und andere wässrige flüssige Abfälle' },
  { value: '19 01 07*', viewValue: 'feste Abfälle aus der Abgasbehandlung' },
  { value: '19 01 10*', viewValue: 'gebrauchte Aktivkohle aus der Abgasbehandlung' },
  { value: '19 01 11*', viewValue: 'Rost- und Kesselaschen sowie Schlacken, die gefährliche Stoffe enthalten' },
  { value: '19 01 12', viewValue: 'Rost- und Kesselaschen sowie Schlacken mit Ausnahme derjenigen, die unter 19 01 11 fallen' },
  { value: '19 01 13*', viewValue: 'Filterstaub, der gefährliche Stoffe enthält' },
  { value: '19 01 14', viewValue: 'Filterstaub mit Ausnahme desjenigen, der unter 19 01 13 fällt' },
  { value: '19 01 15*', viewValue: 'Kesselstaub, der gefährliche Stoffe enthält' },
  { value: '19 01 16', viewValue: 'Kesselstaub mit Ausnahme desjenigen, der unter 19 01 15 fällt' },
  { value: '19 01 17*', viewValue: 'Pyrolyseabfälle, die gefährliche Stoffe enthalten' },
  { value: '19 01 18', viewValue: 'Pyrolyseabfälle mit Ausnahme derjenigen, die unter 19 01 17 fallen' },
  { value: '19 01 19', viewValue: 'Sande aus der Wirbelschichtfeuerung' },
  { value: '19 01 99', viewValue: 'Abfälle a. n. g.' },
  { value: '19 02 03', viewValue: 'vorgemischte Abfälle, die ausschließlich aus nicht gefährlichen Abfällen bestehen' },
  { value: '19 02 04*', viewValue: 'vorgemischte Abfälle, die wenigstens einen gefährlichen Abfall enthalten' },
  { value: '19 02 05*', viewValue: 'Schlämme aus der physikalisch-chemischen Behandlung, die gefährliche Stoffe enthalten' },
  { value: '19 02 06', viewValue: 'Schlämme aus der physikalisch-chemischen Behandlung mit Ausnahme derjenigen, die unter 19 02 05 fallen' },
  { value: '19 02 07*', viewValue: 'Öl und Konzentrate aus Abtrennprozessen' },
  { value: '19 02 08*', viewValue: 'flüssige brennbare Abfälle, die gefährliche Stoffe enthalten' },
  { value: '19 02 09*', viewValue: 'feste brennbare Abfälle, die gefährliche Stoffe enthalten' },
  { value: '19 02 10', viewValue: 'brennbare Abfälle mit Ausnahme derjenigen, die unter 19 02 08 und 19 02 09 fallen' },
  { value: '19 02 11*', viewValue: 'sonstige Abfälle, die gefährliche Stoffe enthalten' },
  { value: '19 02 99', viewValue: 'Abfälle a. n. g.' },
  { value: '19 03 04*', viewValue: 'als gefährlich eingestufte teilweise stabilisierte Abfälle, mit Ausnahme derjenigen, die unter 19 03 08 fallen' },
  { value: '19 03 05', viewValue: 'stabilisierte Abfälle mit Ausnahme derjenigen, die unter 19 03 04 fallen' },
  { value: '19 03 06*', viewValue: 'als gefährlich eingestufte verfestigte Abfälle' },
  { value: '19 03 07', viewValue: 'verfestigte Abfälle mit Ausnahme derjenigen, die unter 19 03 06 fallen' },
  { value: '19 03 08*', viewValue: 'teilweise stabilisiertes Quecksilber' },
  { value: '19 04 01', viewValue: 'verglaste Abfälle' },
  { value: '19 04 02*', viewValue: 'Filterstaub und andere Abfälle aus der Abgasbehandlung' },
  { value: '19 04 03*', viewValue: 'nicht verglaste Festphase' },
  { value: '19 04 04', viewValue: 'wässrige flüssige Abfälle aus dem Tempern' },
  { value: '19 05 01', viewValue: 'nicht kompostierte Fraktion von Siedlungs- und ähnlichen Abfällen' },
  { value: '19 05 02', viewValue: 'nicht kompostierte Fraktion von tierischen und pflanzlichen Abfällen' },
  { value: '19 05 03', viewValue: 'nicht spezifikationsgerechter Kompost' },
  { value: '19 05 99', viewValue: 'Abfälle a. n. g.' },
  { value: '19 06 03', viewValue: 'Flüssigkeiten aus der anaeroben Behandlung von Siedlungsabfällen' },
  { value: '19 06 04', viewValue: 'Gärrückstand/-schlamm aus der anaeroben Behandlung von Siedlungsabfällen' },
  { value: '19 06 05', viewValue: 'Flüssigkeiten aus der anaeroben Behandlung von tierischen und pflanzlichen Abfällen' },
  { value: '19 06 06', viewValue: 'Gärrückstand/-schlamm aus der anaeroben Behandlung von tierischen und pflanzlichen Abfällen' },
  { value: '19 06 99', viewValue: 'Abfälle a. n. g.' },
  { value: '19 07 02*', viewValue: 'Deponiesickerwasser, das gefährliche Stoffe enthält' },
  { value: '19 07 03', viewValue: 'Deponiesickerwasser mit Ausnahme desjenigen, das unter 19 07 02 fällt' },
  { value: '19 08 01', viewValue: 'Sieb- und Rechenrückstände' },
  { value: '19 08 02', viewValue: 'Sandfangrückstände' },
  { value: '19 08 05', viewValue: 'Schlämme aus der Behandlung von kommunalem Abwasser' },
  { value: '19 08 06*', viewValue: 'gesättigte oder verbrauchte Ionenaustauscherharze' },
  { value: '19 08 07*', viewValue: 'Lösungen und Schlämme aus der Regeneration von Ionenaustauschern' },
  { value: '19 08 08*', viewValue: 'schwermetallhaltige Abfälle aus Membransystemen' },
  { value: '19 08 09', viewValue: 'Fett- und Ölmischungen aus Ölabscheidern, die ausschließlich Speiseöle und -fette enthalten' },
  { value: '19 08 10*', viewValue: 'Fett- und Ölmischungen aus Ölabscheidern mit Ausnahme derjenigen, die unter 19 08 09 fallen' },
  { value: '19 08 11*', viewValue: 'Schlämme aus der biologischen Behandlung von industriellem Abwasser, die gefährliche Stoffe enthalten' },
  { value: '19 08 12', viewValue: 'Schlämme aus der biologischen Behandlung von industriellem Abwasser mit Ausnahme derjenigen, die unter 19 08 11 fallen' },
  { value: '19 08 13*', viewValue: 'Schlämme aus einer anderen Behandlung von industriellem Abwasser, die gefährliche Stoffe enthalten' },
  { value: '19 08 14', viewValue: 'Schlämme aus einer anderen Behandlung von industriellem Abwasser mit Ausnahme derjenigen, die unter 19 08 13 fallen' },
  { value: '19 08 99', viewValue: 'Abfälle a. n. g.' },
  { value: '19 09 01', viewValue: 'feste Abfälle aus der Erstfiltration und Siebrückstände' },
  { value: '19 09 02', viewValue: 'Schlämme aus der Wasserklärung' },
  { value: '19 09 03', viewValue: 'Schlämme aus der Dekarbonatisierung' },
  { value: '19 09 04', viewValue: 'gebrauchte Aktivkohle' },
  { value: '19 09 05', viewValue: 'gesättigte oder gebrauchte Ionenaustauscherharze' },
  { value: '19 09 06', viewValue: 'Lösungen und Schlämme aus der Regeneration von Ionenaustauschern' },
  { value: '19 09 99', viewValue: 'Abfälle a. n. g.' },
  { value: '19 10 01', viewValue: 'Eisen- und Stahlabfälle' },
  { value: '19 10 02', viewValue: 'NE-Metall-Abfälle' },
  { value: '19 10 03*', viewValue: 'Schredderleichtfraktionen und Staub, die gefährliche Stoffe enthalten' },
  { value: '19 10 04', viewValue: 'Schredderleichtfraktionen und Staub mit Ausnahme derjenigen, die unter 19 10 03 fallen' },
  { value: '19 10 05*', viewValue: 'andere Fraktionen, die gefährliche Stoffe enthalten' },
  { value: '19 10 06', viewValue: 'andere Fraktionen mit Ausnahme derjenigen, die unter 19 10 05 fallen' },
  { value: '19 11 01*', viewValue: 'gebrauchte Filtertone' },
  { value: '19 11 02*', viewValue: 'Säureteere' },
  { value: '19 11 03*', viewValue: 'wässrige flüssige Abfälle' },
  { value: '19 11 04*', viewValue: 'Abfälle aus der Brennstoffreinigung mit Basen' },
  { value: '19 11 05*', viewValue: 'Schlämme aus der betriebseigenen Abwasserbehandlung, die gefährliche Stoffe enthalten' },
  { value: '19 11 06', viewValue: 'Schlämme aus der betriebseigenen Abwasserbehandlung mit Ausnahme derjenigen, die unter 19 11 05 fallen' },
  { value: '19 11 07*', viewValue: 'Abfälle aus der Abgasreinigung' },
  { value: '19 11 99', viewValue: 'Abfälle a. n. g.' },
  { value: '19 12 01', viewValue: 'Papier und Pappe' },
  { value: '19 12 02', viewValue: 'Eisenmetalle' },
  { value: '19 12 03', viewValue: 'Nichteisenmetalle' },
  { value: '19 12 04', viewValue: 'Kunststoff und Gummi' },
  { value: '19 12 05', viewValue: 'Glas' },
  { value: '19 12 06*', viewValue: 'Holz, das gefährliche Stoffe enthält' },
  { value: '19 12 07', viewValue: 'Holz mit Ausnahme desjenigen, das unter 19 12 06 fällt' },
  { value: '19 12 08', viewValue: 'Textilien' },
  { value: '19 12 09', viewValue: 'Mineralien (z.B. Sand, Steine)' },
  { value: '19 12 10', viewValue: 'brennbare Abfälle (Brennstoffe aus Abfällen)' },
  { value: '19 12 11*', viewValue: 'sonstige Abfälle (einschließlich Materialmischungen) aus der mechanischen Behandlung von Abfällen, die gefährliche Stoffe enthalten' },
  { value: '19 12 12', viewValue: 'sonstige Abfälle (einschließlich Materialmischungen) aus der mechanischen Behandlung von Abfällen mit Ausnahme derjenigen, die unter 19 12 11 fallen' },
  { value: '19 13 01*', viewValue: 'feste Abfälle aus der Sanierung von Böden, die gefährliche Stoffe enthalten' },
  { value: '19 13 02', viewValue: 'feste Abfälle aus der Sanierung von Böden mit Ausnahme derjenigen, die unter 19 13 01 fallen' },
  { value: '19 13 03*', viewValue: 'Schlämme aus der Sanierung von Böden, die gefährliche Stoffe enthalten' },
  { value: '19 13 04', viewValue: 'Schlämme aus der Sanierung von Böden mit Ausnahme derjenigen, die unter 19 13 03 fallen' },
  { value: '19 13 05*', viewValue: 'Schlämme aus der Sanierung von Grundwasser, die gefährliche Stoffe enthalten' },
  { value: '19 13 06', viewValue: 'Schlämme aus der Sanierung von Grundwasser mit Ausnahme derjenigen, die unter 19 13 05 fallen' },
  { value: '19 13 07*', viewValue: 'wässrige flüssige Abfälle und wässrige Konzentrate aus der Sanierung von Grundwasser, die gefährliche Stoffe enthalten' },
  { value: '19 13 08', viewValue: 'wässrige flüssige Abfälle und wässrige Konzentrate aus der Sanierung von Grundwasser mit Ausnahme derjenigen, die unter 19 13 07 fallen' },
  { value: '20 01 01', viewValue: 'Papier und Pappe' },
  { value: '20 01 02', viewValue: 'Glas' },
  { value: '20 01 08', viewValue: 'biologisch abbaubare Küchen- und Kantinenabfälle' },
  { value: '20 01 10', viewValue: 'Bekleidung' },
  { value: '20 01 11', viewValue: 'Textilien' },
  { value: '20 01 13*', viewValue: 'Lösemittel' },
  { value: '20 01 14*', viewValue: 'Säuren' },
  { value: '20 01 15*', viewValue: 'Laugen' },
  { value: '20 01 17*', viewValue: 'Fotochemikalien' },
  { value: '20 01 19*', viewValue: 'Pestizide' },
  { value: '20 01 21*', viewValue: 'Leuchtstoffröhren und andere quecksilberhaltige Abfälle' },
  { value: '20 01 23*', viewValue: 'gebrauchte Geräte, die Fluorchlorkohlenwasserstoffe enthalten' },
  { value: '20 01 26*', viewValue: 'Öle und Fette mit Ausnahme derjenigen, die unter 20 01 25 fallen' },
  { value: '20 01 27*', viewValue: 'Farben, Druckfarben, Klebstoffe und Kunstharze, die gefährliche Stoffe enthalten' },
  { value: '20 01 29*', viewValue: 'Reinigungsmittel, die gefährliche Stoffe enthalten' },
  { value: '20 01 31*', viewValue: 'zytotoxische und zytostatische Arzneimittel' },
  { value: '20 01 33*', viewValue: 'Batterien und Akkumulatoren, die unter 16 06 01, 16 06 02 oder 16 06 03 fallen, sowie gemischte Batterien und Akkumulatoren, die solche Batterien enthalten' },
  { value: '20 01 35*', viewValue: 'gebrauchte elektrische und elektronische Geräte, die gefährliche Bauteile enthalten, mit Ausnahme derjenigen, die unter 20 01 21 und 20 01 23 fallen' },
  { value: '20 01 37*', viewValue: 'Holz, das gefährliche Stoffe enthält' },
  { value: '20 01 39', viewValue: 'Kunststoffe' },
  { value: '20 01 40', viewValue: 'Metalle' },
  { value: '20 01 41', viewValue: 'Abfälle aus der Reinigung von Schornsteinen' },
  { value: '20 02 01', viewValue: 'biologisch abbaubare Abfälle' },
  { value: '20 02 02', viewValue: 'Boden und Steine' },
  { value: '20 02 03', viewValue: 'andere nicht biologisch abbaubare Abfälle' },
  { value: '20 03 01', viewValue: 'gemischte Siedlungsabfälle' },
  { value: '20 03 02', viewValue: 'Marktabfälle' },
  { value: '20 03 03', viewValue: 'Straßenkehricht' },
  { value: '20 03 04', viewValue: 'Fäkalschlamm' },
  { value: '20 03 06', viewValue: 'Abfälle aus der Kanalreinigung' },
  { value: '20 03 07', viewValue: 'Sperrmüll' },
  { value: '20 03 99', viewValue: 'Siedlungsabfälle a. n. g.' },
  ]

  constructor() { }
}
